/* Researcher-only shared task preparation. No rater answers live in this file. */
(function () {
  'use strict';
  const C=window.L2Core,F=window.L2Full,$=id=>document.getElementById(id),ND=C.ND;
  const S={dataset:null,catalogue:null,published:null,tasks:null,identity:'',episode:0,frame:0,tab:'points',marker:0,placement:null,first:null,key:'',revision:0,conflict:false,imageReady:false,load:0,player:null};
  const owner=typeof crypto.randomUUID==='function'?crypto.randomUUID():String(Date.now())+Math.random();
  const pathScope=encodeURIComponent(new URL('.',location.href).pathname);
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ep=()=>S.dataset.episodes[S.episode],le=()=>S.tasks.layout.episodes[S.episode],fr=()=>ep().frames[S.frame],mk=()=>le().markers[S.marker],audit=()=>S.tasks.audits[ep().id];
  const keyFor=id=>'blockmind-l2-setup:'+pathScope+':'+S.dataset.build_id+':'+S.published.task_id+':'+encodeURIComponent(id);
  const read=key=>{let raw;try{raw=localStorage.getItem(key);}catch(_){return {unavailable:true};}if(raw===null)return {empty:true};try{const env=JSON.parse(raw);if(!env||env.schema!=='blockmind_l2_setup_local_v1'||!Number.isInteger(env.revision)||env.revision<1||!env.data)return {invalid:true};return {env};}catch(_){return {invalid:true};}};
  function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),3600);}
  function message(title,text){$('messageTitle').textContent=title;$('messageText').textContent=text;$('messageDialog').showModal();}
  function lock(){S.conflict=true;stop();$('conflictBanner').classList.remove('hidden');$('workspace').classList.add('locked');$('saveStatus').textContent='Editing paused';}
  function save(){
    if(!S.tasks||S.conflict)return false;
    const old=read(S.key);if(old.invalid||(old.env&&old.env.revision!==S.revision)){lock();return false;}
    const revision=S.revision+1;
    try{localStorage.setItem(S.key,JSON.stringify({schema:'blockmind_l2_setup_local_v1',revision,owner,data:S.tasks,ui:{episode:S.episode,frame:S.frame,tab:S.tab,marker:S.marker}}));S.revision=revision;$('storageWarning').classList.add('hidden');$('saveStatus').textContent='Draft saved in this browser';return true;}catch(_){$('storageWarning').classList.remove('hidden');$('saveStatus').textContent='Download to save';return false;}
  }
  function refreshIdentity(){S.tasks.layout.layout_id='';S.tasks.task_id=F.taskId(S.tasks);}
  function changed(invalidateScene=true){if(S.conflict)return;if(invalidateScene)le().setup_reviewed=false;refreshIdentity();save();progress();const summary=$('panelContent').querySelector('.audit-summary');if(summary)summary.innerHTML=auditSummaryHTML(auditSummary());}
  const readyCache=new Map();
  function progress(){if(!S.tasks)return;let ready=0,included=0;const globalReady=S.tasks.settings.protocol_reviewed&&S.tasks.settings.hierarchy_reviewed;S.tasks.layout.episodes.forEach((e,i)=>{if(e.disposition==='include'){included++;if(!globalReady||!e.setup_reviewed)return;const key=C.stableStringify({episode:e,settings:S.tasks.settings,coordinator:S.tasks.coordinator,conditions:S.tasks.layout.conditions}),cached=readyCache.get(e.episode_id);const isReady=cached&&cached.key===key?cached.ready:F.episodeReady(S.tasks,i,S.dataset,S.catalogue).ready;readyCache.set(e.episode_id,{key,ready:isReady});if(isReady)ready++;}});$('overallProgress').textContent=ready+' / '+included+' included scenes ready · '+(S.tasks.layout.episodes.length-included)+' excluded';}
  function accept(tasks,identity,existing){
    S.tasks=tasks;S.identity=identity;S.key=keyFor(identity);S.revision=existing&&existing.env?existing.env.revision:0;S.conflict=false;
    const ui=existing&&existing.env&&existing.env.ui;S.episode=ui&&Number.isInteger(ui.episode)&&ui.episode>=0&&ui.episode<S.dataset.episodes.length?ui.episode:0;S.frame=ui&&Number.isInteger(ui.frame)&&ui.frame>=0&&ui.frame<12?ui.frame:0;S.tab=ui&&['points','directions','boundary','review'].includes(ui.tab)?ui.tab:'points';S.marker=ui&&Number.isInteger(ui.marker)&&ui.marker>=0?ui.marker:0;
    S.tasks.coordinator=identity;S.tasks.layout.coordinator=identity;
    // This is a new/local researcher draft, never a rewrite of published tasks.
    // Preserve all point locations; shortages need real researcher placements.
    S.tasks.settings.points_per_side=4;
    S.tasks.layout.episodes.forEach(e=>{if(e.disposition==='include'&&['indoor','exterior'].some(side=>e.markers.filter(m=>m.side===side).length!==4))e.setup_reviewed=false;});
    refreshIdentity();S.placement=null;S.first=null;
    $('workspace').classList.remove('hidden','locked');$('welcome').classList.add('hidden');$('conflictBanner').classList.add('hidden');
    $('sceneSelect').innerHTML=S.dataset.episodes.map((e,i)=>'<option value="'+i+'">Scene '+(i+1)+' of '+S.dataset.episodes.length+'</option>').join('');render();save();
  }
  function start(event){event.preventDefault();const identity=$('coordinatorInput').value.trim();$('welcomeError').textContent='';if(!identity||identity.length>80){$('welcomeError').textContent='Enter a researcher name or short ID.';return;}const existing=read(keyFor(identity));if(existing.invalid){$('welcomeError').textContent='A saved draft exists but cannot be read. It has not been overwritten. Use a different name or another browser profile to restore a downloaded copy.';return;}let tasks=existing.env?existing.env.data:C.clone(S.published);const errors=F.validateTasks(tasks,S.dataset,S.catalogue,false);if(errors.length){$('welcomeError').textContent='The saved draft needs recovery and has not been changed. '+errors[0];return;}accept(tasks,identity,existing);}
  function stop(){clearInterval(S.player);S.player=null;$('playButton').textContent='▶ Play';}
  function play(){if(S.player){stop();return;}cancelPlacement();if(S.frame===11)frame(0);$('playButton').textContent='Ⅱ Pause';S.player=setInterval(()=>{if(S.frame>=11){stop();return;}frame(S.frame+1);},1100);}
  function frame(index){S.frame=Math.max(0,Math.min(11,index));S.first=null;renderFrame();if(S.tab==='points'||S.tab==='directions'||S.tab==='boundary')renderPanel();save();}
  function scene(index){stop();S.episode=Math.max(0,Math.min(S.dataset.episodes.length-1,index));S.frame=0;S.marker=0;cancelPlacement();render();save();}
  function render(){S.marker=Math.min(S.marker,Math.max(0,le().markers.length-1));$('sceneSelect').value=String(S.episode);$('datasetIdentity').textContent='House '+ep().scan_id+' · fixed boundary object '+ep().boundary_object_id+' · source category '+ep().boundary_class+' (a proposal, not a human label)';document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===S.tab)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});$('filmstrip').innerHTML=ep().frames.map((f,i)=>'<button data-frame="'+i+'" aria-label="Show frame '+(i+1)+'"><img src="'+esc(f.image)+'" alt="" loading="lazy"><span>'+(i+1)+'</span></button>').join('');renderFrame();renderPanel();progress();}
  function renderFrame(){
    const f=fr(),token=++S.load;S.imageReady=false;$('geometryOverlay').innerHTML='';$('imageLoading').textContent='Loading image…';$('imageLoading').classList.remove('hidden');$('imageStage').style.aspectRatio=f.width+' / '+f.height;
    $('frameLabel').textContent='Frame '+(S.frame+1)+' of 12';$('frameSide').textContent=f.side==='indoor'?'Before crossing · indoor':'After crossing · exterior';$('frameSlider').value=S.frame;$('prevFrame').disabled=S.frame===0;$('nextFrame').disabled=S.frame===11;
    $('sceneImage').onload=()=>{const img=$('sceneImage');if(token!==S.load||!img.complete||img.currentSrc!==new URL(f.image,location.href).href)return;if(img.naturalWidth!==f.width||img.naturalHeight!==f.height){$('imageLoading').textContent='Image size mismatch. Geometry editing is disabled.';return;}S.imageReady=true;$('imageLoading').classList.add('hidden');renderGeometry();};
    $('sceneImage').onerror=()=>{if(token===S.load)$('imageLoading').textContent='Could not load this frame.';};$('sceneImage').src=f.image;
    $('maskImage').src=f.boundary_mask;$('maskImage').classList.toggle('hidden',!$('showMask').checked);
    $('nativeHints').textContent='Boundary object '+ep().boundary_object_id+': '+f.boundary_pixels+' first-hit pixels at 160 × 128. Objects: '+f.objects.map(o=>o.name+' [object '+o.object_id+', category '+o.mpcat40+']').join('; ');$('nativeHints').classList.toggle('hidden',!$('showNative').checked);
    document.querySelectorAll('[data-frame]').forEach(b=>b.classList.toggle('active',+b.dataset.frame===S.frame));placementHint();
  }
  function locationFor(m){return m.anchor_frame===fr().id?{x:m.x,y:m.y}:(m.observations||[]).find(o=>o.frame_id===fr().id);}
  function renderGeometry(){
    if(!S.imageReady){$('geometryOverlay').innerHTML='';return;}
    let svg='';
    if(S.tab==='points')le().markers.forEach((m,i)=>{const p=locationFor(m);if(!p)return;const x=p.x*1000,y=p.y*800;svg+='<g data-marker="'+i+'"><circle cx="'+x+'" cy="'+y+'" r="'+(i===S.marker?12:8)+'" fill="#ec3037" stroke="white" stroke-width="3"/><text x="'+(x+16)+'" y="'+(y+5)+'" font-size="21" fill="white" stroke="#172d3a" stroke-width="4" paint-order="stroke" font-weight="700">'+esc(m.id)+'</text></g>';});
    if(S.tab==='directions')le().directions.forEach(d=>{if(d.reference_frame!==fr().id||d.x===null||d.y===null)return;const x=d.x*1000,y=d.y*800;svg+='<circle cx="'+x+'" cy="'+y+'" r="13" fill="#2bb7de" stroke="white" stroke-width="3"/><text x="'+(x+18)+'" y="'+(y+6)+'" font-size="23" fill="white" stroke="#172d3a" stroke-width="4" paint-order="stroke">'+esc(d.id.toUpperCase())+'</text>';});
    if(S.tab==='boundary'||S.tab==='review')le().boundary_boxes.filter(b=>b.frame_id===fr().id).forEach(b=>{svg+='<rect x="'+b.x0*1000+'" y="'+b.y0*800+'" width="'+(b.x1-b.x0)*1000+'" height="'+(b.y1-b.y0)*800+'" fill="none" stroke="#ffe074" stroke-width="4"/>';});
    if(S.first)svg+='<circle cx="'+S.first.x*1000+'" cy="'+S.first.y*800+'" r="7" fill="#ffe074" stroke="white" stroke-width="2"/>';
    $('geometryOverlay').innerHTML=svg;
  }
  function placementHint(){const hints={add:'Click a clear surface to add a point.',move:'Click a new anchor for this point. Old projections will be removed.',observation:'Click the same physical patch in this frame. Do not mark a look-alike surface.',d1:'Click the visible feature that defines direction 1.',d2:'Click the visible feature that defines direction 2.',box:S.first?'Click the opposite corner of the SAME boundary object.':'Click one corner of the boundary object, then the opposite corner.'};$('placementHint').textContent=S.placement?hints[S.placement]:'';$('placementHint').classList.toggle('hidden',!S.placement);$('imageStage').style.cursor=S.placement?'crosshair':'';}
  function cancelPlacement(){S.placement=null;S.first=null;placementHint();renderGeometry();}
  function begin(kind){if(S.conflict)return;stop();if((kind==='move'||kind==='observation')&&!mk())return;if(kind==='add'&&areaCount(fr().side)>=4){message('Four points already selected on this side','Move or remove an existing point before adding another. The shared task needs exactly 4 surface patches per side.');return;}if(kind==='box'&&fr().side!=='indoor'){message('Choose a pre-crossing frame','Opening boxes must include at least two frames before the crossing. Select frames 1–6.');return;}if(kind==='move'&&(mk().observations||[]).length&&!confirm('Moving the anchor clears its projected locations in other frames. Continue?'))return;S.placement=kind;S.first=null;placementHint();renderGeometry();}
  function field(title,id,value,attrs=''){return '<label class="field" for="'+id+'">'+esc(title)+'<input id="'+id+'" value="'+esc(value)+'" '+attrs+'></label>';}
  function areaCount(side){return le().markers.filter(m=>m.side===side).length;}
  function pointHTML(){
    const inside=areaCount('indoor'),outside=areaCount('exterior'),m=mk();let html='<p class="eyebrow">Shared targets</p><h2>Review the surface points</h2><p class="step-description">Choose exactly 4 distinct physical surface patches on each side. Both annotators will see these same locked points. Suggested locations still need your review; missing points are never invented automatically.</p><div class="setup-counts"><span class="count-chip'+(inside!==4?' warn':'')+'">Indoor: '+inside+' / 4</span><span class="count-chip'+(outside!==4?' warn':'')+'">Exterior: '+outside+' / 4</span></div>';
    html+='<div class="point-list">'+le().markers.map((p,i)=>'<button data-select-marker="'+i+'" class="'+(i===S.marker?'selected':'')+'">'+esc(p.id)+'</button>').join('')+'</div><div class="button-row"><button id="addPoint" class="primary"'+(areaCount(fr().side)>=4?' disabled title="Four points on this side: move or remove one to replace it."':'')+'>Add point</button>'+(m?'<button id="movePoint">Move anchor</button><button id="deletePoint" class="danger-button">Delete point</button>':'')+'</div>';
    if(m){const anchor=ep().frames.find(f=>f.id===m.anchor_frame);html+='<h3>'+esc(m.id)+' · '+(m.side==='indoor'?'Indoor':'Exterior')+'</h3><p class="setup-note">Anchor: frame '+anchor.index+' · native object '+(m.object_id===null?'not assigned':m.object_id)+'. Moving a point clears its old machine instance and projected locations.</p><div class="button-row"><button id="showAnchor">Show anchor</button><button id="addObservation">Mark this same patch in current frame</button></div><p class="question-hint">For another view, change the frame first, then click “Mark this same patch”. Mark only when you can genuinely identify the same patch; leaving it unmarked does not mean it is invisible.</p><table class="mini-table"><thead><tr><th>View</th><th>Location source</th><th></th></tr></thead><tbody><tr><td>Frame '+anchor.index+'</td><td>Anchor</td><td><button data-go-frame="'+(anchor.index-1)+'">Show</button></td></tr>'+(m.observations||[]).filter(o=>o.frame_id!==m.anchor_frame).map(o=>{const f=ep().frames.find(v=>v.id===o.frame_id);return '<tr><td>Frame '+f.index+'</td><td>'+esc(o.source)+'</td><td><button data-go-frame="'+(f.index-1)+'">Show</button> <button data-delete-observation="'+esc(o.frame_id)+'">Remove</button></td></tr>';}).join('')+'</tbody></table>';}
    return html+'<div class="actions"><button data-next-tab="directions" class="primary">Next: directions →</button></div>';
  }
  function directionsHTML(){let html='<p class="eyebrow">Shared scenario definitions</p><h2>Define the same two directions</h2><p class="step-description">Use the approved feature-relative wording. State where sunlight and rain come from, tied to something visible—for example, “Coming in sideways from the open side of the terrace beside the railing.” Use an example only if it matches this scene. Pick that visible reference feature in the image. The annotator arrow points to this feature; it is not a simulated travel vector. Blank or unapproved directions cannot be used for physics questions.</p>';
    le().directions.forEach((d,i)=>{html+='<section class="direction-card"><h3>Direction '+(i+1)+'</h3><label class="field" for="directionText_'+d.id+'">Prompt wording<textarea id="directionText_'+d.id+'" data-direction="'+d.id+'" maxlength="4000" placeholder="Define the direction relative to a visible feature…">'+esc(d.text)+'</textarea></label><p class="direction-reference">'+(d.x===null?'No reference anchor yet.':'Reference: frame '+parseInt(d.reference_frame.slice(1),10)+' at ('+d.x.toFixed(3)+', '+d.y.toFixed(3)+').')+'</p><div class="button-row"><button id="placeDirection_'+d.id+'" data-place-direction="'+d.id+'">Place reference in this image</button>'+(d.x!==null?'<button data-show-direction="'+d.id+'">Show reference</button>':'')+'</div><details class="optional"><summary>Draft wording helper — not an approved direction</summary><p class="setup-note">These are starting points only. Replace bracketed features and make the geometry unambiguous before approving the protocol.</p><button data-draft-direction="'+d.id+'" data-draft="above">From above</button> <button data-draft-direction="'+d.id+'" data-draft="opening">From the open side</button></details></section>';});
    html+='<details class="optional"><summary>Fixed open / sealed conditions</summary><p class="setup-note"><strong>Open:</strong> '+esc(S.tasks.layout.conditions.open)+'</p><p class="setup-note"><strong>Sealed:</strong> '+esc(S.tasks.layout.conditions.sealed)+'</p><p class="setup-note">'+esc(S.tasks.layout.conditions.no_closure_policy)+'</p></details><div class="actions"><button data-next-tab="points">← Points</button><button data-next-tab="boundary" class="primary">Next: opening →</button></div>';return html;
  }
  function boundaryHTML(){return '<p class="eyebrow">One fixed boundary</p><h2>Check the opening boxes</h2><p class="step-description">Outline boundary object <strong>'+ep().boundary_object_id+'</strong> in at least two different pre-crossing frames. Use the same door or opening throughout, not a neighboring one.</p><p class="setup-note">This native object identity is fixed by the dataset. If it is wrong, flag the scene and exclude it; do not silently switch objects.</p><div class="button-row"><button id="drawBox" class="primary">Draw / replace box in this image</button><button id="cancelPlacement">Cancel drawing</button></div><table class="mini-table"><thead><tr><th>Frame</th><th>Position in sequence</th><th></th></tr></thead><tbody>'+le().boundary_boxes.map(b=>{const f=ep().frames.find(v=>v.id===b.frame_id);return '<tr><td>'+f.index+'</td><td>'+(f.side==='indoor'?'Before crossing':'After crossing')+'</td><td><button data-go-frame="'+(f.index-1)+'">Show</button> <button data-delete-box="'+esc(b.frame_id)+'">Remove</button></td></tr>';}).join('')+'</tbody></table><p class="question-hint">Click two opposite corners. The machine mask can help locate the candidate, but it does not certify transparency, a physical pane or actual visibility.</p><div class="actions"><button data-next-tab="directions">← Directions</button><button data-next-tab="review" class="primary">Next: review →</button></div>';}
  function auditChoice(title,path,value){return '<div class="audit-question"><span>'+esc(title)+'</span><div class="choices">'+['yes','no',ND].map(v=>'<button data-audit="'+path+'" data-value="'+v+'" class="choice'+(value===v?' selected':'')+'" aria-pressed="'+(value===v)+'">'+(v==='yes'?'Yes':v==='no'?'No':'Not determinable')+'</button>').join('')+'</div></div>';}
  function auditSummary(){
    const values=Object.values(S.tasks.audits),selected=values.filter(a=>a.glass.selected).map(a=>a.glass);
    const fields=['pane_present','phantom_geometry','separate_leaf'],explicit=v=>['yes','no',ND].includes(v),positive=g=>g.pane_present==='yes'||g.separate_leaf==='yes';
    const completed=selected.filter(g=>fields.every(k=>explicit(g[k]))&&(g.evidence_frames.length>0||g.notes.trim().length>0));
    const uncertain=completed.filter(g=>fields.some(k=>g[k]===ND)).length;
    const passes=completed.filter(g=>positive(g)&&fields.every(k=>g[k]!==ND)).length;
    const trajectories=values.filter(a=>a.trajectory.selected).map(a=>a.trajectory);
    const trajectory={selected:trajectories.length,yes:trajectories.filter(t=>t.valid==='yes').length,no:trajectories.filter(t=>t.valid==='no').length,uncertain:trajectories.filter(t=>t.valid===ND).length};
    trajectory.reviewed=trajectory.yes+trajectory.no+trajectory.uncertain;trajectory.pending=trajectory.selected-trajectory.reviewed;
    return {selected:selected.length,completed:completed.length,pending:selected.length-completed.length,uncertain,positive_descriptive:selected.filter(positive).length,passes,ratio:completed.length?passes/completed.length:null,trajectory,gate:completed.length>=20&&passes/completed.length>=.7};
  }
  function auditSummaryHTML(summary){return '<strong>Dataset audit coverage</strong><br>'+summary.selected+' boundaries selected · '+summary.completed+' completed · '+summary.pending+' still pending.<br>Completed means all three answers plus an evidence frame or written note. '+summary.uncertain+' completed records contain uncertainty.<br>'+summary.positive_descriptive+' selected records say pane or separate leaf is present (descriptive only).<br>Conservative gate: '+summary.passes+' fully determined positives / '+summary.completed+' completed'+(summary.ratio===null?'':(' ('+(100*summary.ratio).toFixed(1)+'%)'))+'. Uncertain records stay in the denominator, not the passing count.<br>Target: at least 20 completed reviews and at least 70% confirmed.<br><strong>'+(summary.gate?'Numeric gate met — inspect evidence before enabling downstream helpers.':'Gate not met.')+'</strong><br>Trajectory audit: '+summary.trajectory.selected+' selected · '+summary.trajectory.reviewed+' reviewed ('+summary.trajectory.yes+' yes, '+summary.trajectory.no+' no, '+summary.trajectory.uncertain+' not determinable) · '+summary.trajectory.pending+' pending.<br>These audit gates do not block annotation publication. External G3 coverage has not been assessed here.';}
  function readyMessages(){const result=F.episodeReady(S.tasks,S.episode,S.dataset,S.catalogue);return '<div class="readiness'+(result.ready?' ready':'')+'"><strong>'+(result.ready?'This scene is ready for shared annotation.':'Still needed before shared collection can finish:')+'</strong>'+(result.ready?'':'<ul>'+result.errors.slice(0,8).map(e=>'<li>'+esc(e)+'</li>').join('')+(result.errors.length>8?'<li>Additional missing setup items remain.</li>':'')+'</ul>')+'</div>';}
  function reviewHTML(){const a=audit(),summary=auditSummary(),settings=S.tasks.settings,excluded=le().disposition==='exclude';let html='<p class="eyebrow">Researcher checks</p><h2>Review this scene</h2><p class="step-description">Approve shared geometry only after inspecting it. These setup decisions and audits are not annotator votes.</p>';
    if(ep().quality_note)html+='<p class="source-warning">Source review note: '+esc(ep().quality_note)+'</p>';
    const evidenceLinks=[['Boundary mask audit',ep().audit_links.boundary_audit],['Route map',ep().audit_links.route_map],['Navigation evidence',ep().audit_links.navigation],['Native instance lookup',ep().geometry_assets.instance_lookup],['Raycast helper arrays',ep().geometry_assets.raycast_cache]];
    html+='<details class="optional"><summary>Open source evidence for researcher inspection</summary><div class="button-row">'+evidenceLinks.filter(v=>typeof v[1]==='string'&&v[1].startsWith('data/')).map(([name,path])=>'<a href="'+esc(path)+'" target="_blank" rel="noopener">'+esc(name)+'</a>').join(' · ')+'</div><p class="setup-note">These source files are supporting evidence, not a substitute for inspecting the actual mesh when deciding pane / leaf representation.</p></details>';
    html+='<label class="checkline"><input id="excludeScene" type="checkbox"'+(excluded?' checked':'')+'><span>Exclude this scene from collection</span></label>';
    if(excluded)html+='<label class="field">Reason for exclusion<textarea id="exclusionReason" maxlength="8000">'+esc(le().exclusion_reason)+'</textarea></label>';
    html+='<label class="checkline"><input id="setupReviewed" type="checkbox"'+(le().setup_reviewed?' checked':'')+'><span><strong>I reviewed this scene’s points, directions and opening boxes.</strong><small>Changing geometry or direction wording clears this approval.</small></span></label><label class="field">Setup notes<textarea id="setupNotes" maxlength="8000">'+esc(le().setup_notes)+'</textarea></label>'+readyMessages();
    html+='<p class="setup-note"><a href="review.html">Later: output-matcher audit, human baseline and error review →</a></p>';
    html+='<section class="audit-section"><h3>T4 · Trajectory spot-check</h3><label class="checkline"><input id="trajectorySelected" type="checkbox"'+(a.trajectory.selected?' checked':'')+'>Include this scene in the trajectory audit</label>'+auditChoice('Is the selected trajectory valid?','trajectory.valid',a.trajectory.valid)+'<label class="field">Trajectory evidence / notes<textarea id="trajectoryNotes" maxlength="8000">'+esc(a.trajectory.notes)+'</textarea></label></section>';
    html+='<section class="audit-section"><h3>T2 · Glass / leaf mesh audit</h3><p class="setup-note">Inspect geometry evidence, not RGB appearance alone. The mask by itself does not prove that a pane or separate moving leaf exists.</p><label class="checkline"><input id="glassSelected" type="checkbox"'+(a.glass.selected?' checked':'')+'>Include this boundary in the glass audit</label>'+auditChoice('Does the geometry contain the pane?','glass.pane_present',a.glass.pane_present)+auditChoice('Is there phantom geometry at the opening?','glass.phantom_geometry',a.glass.phantom_geometry)+auditChoice('Is a separate door / moving leaf represented?','glass.separate_leaf',a.glass.separate_leaf)+'<p class="small"><strong>Evidence frames</strong></p><div class="evidence-frames">'+ep().frames.map(f=>'<label><input type="checkbox" data-evidence="'+f.id+'"'+(a.glass.evidence_frames.includes(f.id)?' checked':'')+'>'+f.index+'</label>').join('')+'</div><label class="field">Geometry evidence / notes<textarea id="glassNotes" maxlength="8000">'+esc(a.glass.notes)+'</textarea></label><div class="audit-summary">'+auditSummaryHTML(summary)+'</div><div class="button-row"><button id="exportGlassCSV">Export glass audit CSV</button><button id="exportReviewCSV">Export trajectory / review CSV</button></div></section>';
    html+='<details class="global-settings"><summary>One-time protocol & material reference review</summary><p class="setup-note">These approvals apply to the whole shared task package. They do not invent the missing thermal comparison table or additional protocol details.</p><label class="checkline"><input id="protocolReviewed" type="checkbox"'+(settings.protocol_reviewed?' checked':'')+'><span>I reviewed the actual direction definitions, open/sealed assumptions and collection protocol.</span></label>'+field('Protocol reviewer','protocolReviewer',settings.protocol_reviewer,'maxlength="200"')+'<label class="field">Protocol notes / unresolved choices<textarea id="protocolNotes" maxlength="8000">'+esc(settings.protocol_notes)+'</textarea></label><label class="checkline"><input id="hierarchyReviewed" type="checkbox"'+(settings.hierarchy_reviewed?' checked':'')+'><span>I reviewed the material reference hierarchy for this collection.</span></label>'+field('Material reference reviewer','hierarchyReviewer',settings.hierarchy_reviewer,'maxlength="200"')+'<details class="optional"><summary>View '+S.catalogue.materials.length+' material reference entries</summary><div class="table-scroll"><table class="mini-table"><thead><tr><th>Material</th><th>Reference family</th></tr></thead><tbody>'+S.catalogue.materials.map(m=>'<tr><td>'+esc(m.label)+'</td><td>'+esc(m.family)+'</td></tr>').join('')+'</tbody></table></div><p class="setup-note"><a href="catalogue.json" target="_blank" rel="noopener">Open full material reference file</a></p></details><p class="setup-note">Approved thermal comparison pairs: '+esc(settings.vhc_allowed_pairs_status)+'. Annotation collection can proceed; thermal benchmark GT still needs its separately approved mapping and pairs.</p></details><div class="actions"><button data-next-tab="boundary">← Opening boxes</button><button id="nextScene" class="primary">Next scene →</button></div>';return html;
  }
  function renderPanel(){const openDetails=new Set([...$('panelContent').querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent));const active=document.activeElement,focusId=active.id,focusAudit=active.dataset&&active.dataset.audit,focusValue=active.dataset&&active.dataset.value;$('panelContent').innerHTML=S.tab==='points'?pointHTML():S.tab==='directions'?directionsHTML():S.tab==='boundary'?boundaryHTML():reviewHTML();$('panelContent').querySelectorAll('details').forEach(d=>{if(openDetails.has(d.querySelector('summary')?.textContent))d.open=true;});const restored=focusId?$(focusId):focusAudit?[...$('panelContent').querySelectorAll('[data-audit]')].find(b=>b.dataset.audit===focusAudit&&b.dataset.value===focusValue):null;if(restored)restored.focus({preventScroll:true});renderGeometry();}
  function tab(name){stop();cancelPlacement();S.tab=name;render();save();}
  function selectMarker(index){S.marker=Math.max(0,Math.min(le().markers.length-1,index));const m=mk();if(m)S.frame=ep().frames.findIndex(f=>f.id===m.anchor_frame);cancelPlacement();renderFrame();renderPanel();save();}
  function pointClick(event){
    const selected=event.target.closest('[data-marker]');if(selected&&!S.placement){selectMarker(+selected.dataset.marker);return;}
    if(!S.placement||S.conflict||!S.imageReady)return;const img=$('sceneImage'),f=fr();if(!img.complete||img.currentSrc!==new URL(f.image,location.href).href||img.naturalWidth!==f.width||img.naturalHeight!==f.height)return;
    const rect=img.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;if(x<0||x>1||y<0||y>1)return;
    if(S.placement==='add'){const side=f.side,prefix=side==='indoor'?'I':'E';if(areaCount(side)>=4){message('Four points already selected on this side','Move or remove an existing point before adding another. The shared task needs exactly 4 surface patches per side.');return;}let n=1;while(le().markers.some(m=>m.id===prefix+n))n++;le().markers.push({id:prefix+n,side,anchor_frame:f.id,x,y,object_id:null,mpcat40:null,observations:[]});S.marker=le().markers.length-1;}
    else if(S.placement==='move'){if(f.side!==mk().side){message('Choose a frame on the same side','Move an indoor point in an indoor frame, or an exterior point in an exterior frame.');return;}Object.assign(mk(),{anchor_frame:f.id,x,y,object_id:null,mpcat40:null,observations:[]});}
    else if(S.placement==='observation'){if(f.id===mk().anchor_frame){message('This is the anchor frame','Use Move anchor to change this view, or select a different frame to add a same-surface observation.');return;}mk().observations=mk().observations.filter(o=>o.frame_id!==f.id);mk().observations.push({frame_id:f.id,x,y,source:'human'});}
    else if(S.placement==='d1'||S.placement==='d2'){const d=le().directions.find(v=>v.id===S.placement);Object.assign(d,{reference_frame:f.id,x,y});}
    else if(S.placement==='box'){if(f.side!=='indoor'){message('Select a pre-crossing frame','Draw boxes in frames 1–6.');return;}if(!S.first){S.first={x,y};placementHint();renderGeometry();return;}const b={frame_id:f.id,x0:Math.min(x,S.first.x),y0:Math.min(y,S.first.y),x1:Math.max(x,S.first.x),y1:Math.max(y,S.first.y)};if(b.x1-b.x0<1/f.width||b.y1-b.y0<1/f.height){message('The box is too small','Click two distinct opposite corners around the boundary object.');return;}le().boundary_boxes=le().boundary_boxes.filter(v=>v.frame_id!==f.id);le().boundary_boxes.push(b);le().boundary_boxes.sort((a,b)=>a.frame_id.localeCompare(b.frame_id));}
    cancelPlacement();changed();renderPanel();renderGeometry();toast('Shared geometry updated. Review this scene again before publishing.');
  }
  function downloadJSON(doc,filename){const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function draftExport(){if(!S.tasks)return;const errors=F.validateTasks(S.tasks,S.dataset,S.catalogue,false);if(errors.length){message('Draft needs recovery',errors.slice(0,6).join('\n'));return;}downloadJSON(S.tasks,'collection-tasks-draft-'+new Date().toISOString().slice(0,10)+'.json');}
  function publish(){
    if(S.conflict){message('This tab is paused','Download this copy or load the saved draft before publishing.');return;}
    const candidate=C.clone(S.tasks);candidate.layout.layout_id=C.layoutId(candidate.layout);candidate.task_id=F.taskId(candidate);
    const errors=F.validateTasks(candidate,S.dataset,S.catalogue,true);
    candidate.layout.episodes.forEach((e,i)=>{if(e.disposition==='include'&&e.directions.some(d=>/UNAPPROVED DRAFT|\[name the visible/i.test(d.text)))errors.unshift('Scene '+(i+1)+': replace draft direction placeholders with reviewed feature-relative wording.');});
    if(errors.length){message('Research setup is not ready to publish','Review the missing items below. You can still download a draft at any time.\n\n'+errors.slice(0,8).join('\n')+(errors.length>8?'\n…more scenes also need review.':''));return;}
    if(!confirm('Publish these reviewed shared tasks? Both raters must use this same file. After collection starts, changing geometry or directions requires a new task version and explicit migration.'))return;
    downloadJSON(candidate,'collection-tasks.json');message('Reviewed task file downloaded','Copy the downloaded collection-tasks.json into this website folder, replacing the existing file. Then reload the annotator page.\n\nThis browser cannot update the server file itself. Local setup changes are not automatically published.');
  }
  function csvCell(value){let text=String(value==null?'':value);if(/^[=+\-@\t\r]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';}
  function csvDownload(kind){const glass=kind==='glass',headers=glass?['episode_id','house','boundary_object_id','selected','pane_present','phantom_geometry','separate_leaf','evidence_frames','notes']:['episode_id','house','boundary_object_id','disposition','exclusion_reason','setup_reviewed','trajectory_selected','trajectory_valid','trajectory_notes','setup_notes'];const rows=S.dataset.episodes.map((e,i)=>{const a=S.tasks.audits[e.id],l=S.tasks.layout.episodes[i];return glass?[e.id,e.scan_id,e.boundary_object_id,a.glass.selected,a.glass.pane_present,a.glass.phantom_geometry,a.glass.separate_leaf,a.glass.evidence_frames.join(';'),a.glass.notes]:[e.id,e.scan_id,e.boundary_object_id,l.disposition,l.exclusion_reason,l.setup_reviewed,a.trajectory.selected,a.trajectory.valid,a.trajectory.notes,l.setup_notes];});const content=[headers,...rows].map(row=>row.map(csvCell).join(',')).join('\r\n');const blob=new Blob([content],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=glass?'glass_geometry_audit.csv':'trajectory_and_scene_review.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function importFile(file){if(!file)return;if(file.size>40*1024*1024){message('File is too large','Choose a shared task JSON smaller than 40 MB.');return;}let tasks;try{tasks=JSON.parse(await file.text());}catch(_){message('Could not read this file','Select a downloaded shared task JSON.');return;}const errors=F.validateTasks(tasks,S.dataset,S.catalogue,false);if(errors.length){message('This task file cannot be opened',errors.slice(0,5).join('\n'));return;}if(S.conflict){message('This tab is paused','Download this copy or load the saved draft first.');return;}if(!confirm('Replace your local researcher draft with this task file? Download your current draft first if you need both versions.'))return;const existing=read(S.key);if(existing.invalid||(existing.env&&existing.env.revision!==S.revision)){lock();return;}accept(tasks,S.identity,existing);toast('Imported into your local draft only. The published file is unchanged.');}
  $('startForm').addEventListener('submit',start);$('closeMessage').addEventListener('click',()=>$('messageDialog').close());$('sceneSelect').addEventListener('change',e=>scene(+e.target.value));$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)tab(b.dataset.tab);});$('prevFrame').addEventListener('click',()=>{stop();frame(S.frame-1);});$('nextFrame').addEventListener('click',()=>{stop();frame(S.frame+1);});$('playButton').addEventListener('click',play);$('frameSlider').addEventListener('input',e=>{stop();frame(+e.target.value);});$('filmstrip').addEventListener('click',e=>{const b=e.target.closest('[data-frame]');if(b){stop();frame(+b.dataset.frame);}});$('imageStage').addEventListener('click',pointClick);$('showMask').addEventListener('change',()=>$('maskImage').classList.toggle('hidden',!$('showMask').checked));$('showNative').addEventListener('change',()=>$('nativeHints').classList.toggle('hidden',!$('showNative').checked));$('draftExport').addEventListener('click',draftExport);$('recoveryExport').addEventListener('click',draftExport);$('publishButton').addEventListener('click',publish);$('importButton').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',async e=>{await importFile(e.target.files[0]);e.target.value='';});
  $('reloadLatest').addEventListener('click',()=>{const stored=read(S.key);if(!stored.env||F.validateTasks(stored.env.data,S.dataset,S.catalogue,false).length){message('The saved copy cannot be loaded','Download this tab’s copy. The existing saved draft has not been overwritten.');return;}if(confirm('Replace this tab’s work with the saved draft? Download a copy first if needed.'))accept(stored.env.data,S.identity,stored);});
  $('panelContent').addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||S.conflict)return;
    if(b.dataset.selectMarker!==undefined){selectMarker(+b.dataset.selectMarker);return;}
    if(b.dataset.nextTab){tab(b.dataset.nextTab);return;}
    if(b.dataset.goFrame!==undefined){stop();frame(+b.dataset.goFrame);return;}
    if(b.dataset.placeDirection){begin(b.dataset.placeDirection);return;}
    if(b.dataset.showDirection){const d=le().directions.find(v=>v.id===b.dataset.showDirection);frame(ep().frames.findIndex(f=>f.id===d.reference_frame));return;}
    if(b.dataset.draftDirection){const d=le().directions.find(v=>v.id===b.dataset.draftDirection);if(d.text&&!confirm('Replace this direction’s current wording with an unapproved draft?'))return;d.text=b.dataset.draft==='above'?'UNAPPROVED DRAFT: vertically downward from the sky above [name the visible reference feature].':'UNAPPROVED DRAFT: from the exterior open side toward the interior through [name the visible boundary feature].';changed();renderPanel();return;}
    if(b.dataset.deleteObservation){mk().observations=mk().observations.filter(o=>o.frame_id!==b.dataset.deleteObservation);changed();renderPanel();return;}
    if(b.dataset.deleteBox){le().boundary_boxes=le().boundary_boxes.filter(v=>v.frame_id!==b.dataset.deleteBox);changed();renderPanel();return;}
    if(b.dataset.audit){const [section,key]=b.dataset.audit.split('.');audit()[section][key]=audit()[section][key]===b.dataset.value?null:b.dataset.value;changed(false);renderPanel();return;}
    switch(b.id){case 'addPoint':begin('add');break;case 'movePoint':begin('move');break;case 'deletePoint':if(mk()&&confirm('Delete '+mk().id+' and all of its cross-frame locations from the shared draft?')){le().markers.splice(S.marker,1);S.marker=Math.min(S.marker,Math.max(0,le().markers.length-1));cancelPlacement();changed();renderPanel();}break;case 'showAnchor':selectMarker(S.marker);break;case 'addObservation':begin('observation');break;case 'drawBox':begin('box');break;case 'cancelPlacement':cancelPlacement();break;case 'exportGlassCSV':csvDownload('glass');break;case 'exportReviewCSV':csvDownload('review');break;case 'nextScene':scene(S.episode===S.dataset.episodes.length-1?0:S.episode+1);break;}
  });
  $('panelContent').addEventListener('change',e=>{if(S.conflict)return;const t=e.target;
    if(t.dataset.evidence){audit().glass.evidence_frames=t.checked?[...new Set([...audit().glass.evidence_frames,t.dataset.evidence])].sort():audit().glass.evidence_frames.filter(id=>id!==t.dataset.evidence);changed(false);return;}
    const checked=t.checked;switch(t.id){case 'excludeScene':le().disposition=checked?'exclude':'include';if(!checked)le().exclusion_reason='';changed();renderPanel();break;case 'setupReviewed':if(checked&&le().disposition==='include'&&['indoor','exterior'].some(side=>areaCount(side)!==4)){t.checked=false;le().setup_reviewed=false;message('Exactly four points are needed on each side','This scene has '+areaCount('indoor')+' indoor and '+areaCount('exterior')+' exterior points. Review and place the missing real surface patches before approving, or exclude the scene with a reason.');}else le().setup_reviewed=checked;changed(false);renderPanel();break;case 'trajectorySelected':audit().trajectory.selected=checked;changed(false);renderPanel();break;case 'glassSelected':audit().glass.selected=checked;changed(false);renderPanel();break;case 'protocolReviewed':S.tasks.settings.protocol_reviewed=checked;if(checked&&!S.tasks.settings.protocol_reviewer)S.tasks.settings.protocol_reviewer=S.identity;changed(false);renderPanel();break;case 'hierarchyReviewed':S.tasks.settings.hierarchy_reviewed=checked;if(checked&&!S.tasks.settings.hierarchy_reviewer)S.tasks.settings.hierarchy_reviewer=S.identity;changed(false);renderPanel();break;}
  });
  $('panelContent').addEventListener('input',e=>{if(S.conflict)return;const t=e.target;if(t.dataset.direction){le().directions.find(d=>d.id===t.dataset.direction).text=t.value;changed();return;}const paths={setupNotes:['layout','setup_notes'],exclusionReason:['layout','exclusion_reason'],trajectoryNotes:['trajectory','notes'],glassNotes:['glass','notes'],protocolReviewer:['settings','protocol_reviewer'],hierarchyReviewer:['settings','hierarchy_reviewer'],protocolNotes:['settings','protocol_notes']};const p=paths[t.id];if(!p)return;if(p[0]==='layout')le()[p[1]]=t.value;else if(p[0]==='settings'){S.tasks.settings[p[1]]=t.value;if(!t.value.trim()&&t.id==='protocolReviewer'){S.tasks.settings.protocol_reviewed=false;$('protocolReviewed').checked=false;}if(!t.value.trim()&&t.id==='hierarchyReviewer'){S.tasks.settings.hierarchy_reviewed=false;$('hierarchyReviewed').checked=false;}}else audit()[p[0]][p[1]]=t.value;changed(p[0]==='layout'&&p[1]!=='setup_notes');});
  window.addEventListener('storage',e=>{if(S.tasks&&e.key===S.key){const stored=read(S.key);if(!stored.env||stored.env.revision!==S.revision)lock();}});window.addEventListener('beforeunload',e=>{if(S.tasks&&(!save()||S.conflict)){e.preventDefault();e.returnValue='';}});document.addEventListener('keydown',e=>{if(!S.tasks||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||$('messageDialog').open)return;if(e.key==='Escape')cancelPlacement();if(e.key==='ArrowLeft'){stop();frame(S.frame-1);}if(e.key==='ArrowRight'){stop();frame(S.frame+1);}});
  window.L2Setup=Object.freeze({getSnapshot:()=>C.clone({tasks:S.tasks,identity:S.identity,episode:S.episode,frame:S.frame,tab:S.tab,marker:S.marker,placement:S.placement,first:S.first,imageReady:S.imageReady,key:S.key,revision:S.revision,conflict:S.conflict}),getDataset:()=>C.clone(S.dataset)});
  Promise.all(['dataset.json','catalogue.json','collection-tasks.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw new Error('Could not load '+url);return r.json();}))).then(([dataset,catalogue,published])=>{if(!F)throw new Error('The shared task schema did not load.');const errors=F.validateTasks(published,dataset,catalogue,false);if(errors.length)throw new Error(errors[0]);S.dataset=dataset;S.catalogue=catalogue;S.published=published;$('loading').classList.add('hidden');$('welcome').classList.remove('hidden');}).catch(e=>{$('loading').classList.add('hidden');$('fatal').textContent='Could not open researcher setup. Serve the website folder over HTTP and confirm its shared task files are present. '+e.message;$('fatal').classList.remove('hidden');});
})();
