'use strict';
// Synthetic fixtures only: no deployed tasks, human votes or approval flags are changed.
const assert=require('assert'),C=require('../core.js'),F=require('../full-core.js');
const dataset={build_id:'provisional-collection-test',episodes:[{id:'sample',frames:C.FRAMES.map((id,i)=>({id,side:i<6?'indoor':'exterior',boundary_pixels:150,boundary_bbox:[.1,.1,.6,.8],objects:[{object_id:1,mpcat40:3}]})),proposed_markers:['indoor','exterior'].flatMap(side=>[1,2,3,4].map(n=>({id:(side==='indoor'?'I':'E')+n,side,anchor_frame:side==='indoor'?'f01':'f07',x:n/5,y:.4,object_id:1,mpcat40:3,observations:[]})))}]};
const catalogue={build_id:dataset.build_id,materials:[{id:'wood',name:'Wood'}]};
function rehash(tasks){tasks.layout.layout_id=C.layoutId(tasks.layout);tasks.task_id=F.taskId(tasks);return tasks;}
function provisional(){const t=F.createTasks(dataset,catalogue,'Shared task coordinator');Object.assign(t.settings,{collection_mode:'provisional',points_per_side:4});t.layout.episodes[0].directions=[{id:'d1',text:'From the left side of the marked opening toward the indoor room.',reference_frame:'f06',x:.1,y:.45},{id:'d2',text:'From above the marked opening downward toward the floor.',reference_frame:'f06',x:.35,y:.1}];return rehash(t);}
function changed(tasks,fn){const result=C.clone(tasks);fn(result);return rehash(result);}
function blank(tasks=provisional()){return F.create(dataset,catalogue,tasks,'annotator-A');}
function fill(doc){for(const q of F.questions(doc,0,dataset,catalogue))F.setAnswer(doc,0,q.path,q.kind==='multiselect'?[C.ND]:C.ND);doc.episodes[0].answers.notes='Synthetic test: uncertainty is intentional.';doc.episodes[0].status='complete';doc.episodes[0].completed_at=new Date().toISOString();doc.annotation_status='complete';return doc;}
function ready(tasks){return F.episodeCollectionReady(tasks,0,dataset,catalogue);}
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('collection mode absent or reviewed retains strict legacy approval gates',()=>{for(const mode of [undefined,'reviewed']){const tasks=provisional();if(mode===undefined)delete tasks.settings.collection_mode;else tasks.settings.collection_mode=mode;rehash(tasks);assert(!ready(tasks).ready);assert.deepStrictEqual(ready(tasks),F.episodeReady(tasks,0,dataset,catalogue));assert(F.questions(blank(tasks),0,dataset,catalogue).filter(q=>q.section==='exposure').every(q=>q.blocked));}});
test('optional collection mode rejects invalid values without weakening schemas',()=>{for(const value of [null,true,1,'automatic','approved',{},[]]){const tasks=changed(provisional(),t=>t.settings.collection_mode=value);assert(F.validateTasks(tasks,dataset,catalogue).some(e=>e.includes('collection_mode')));assert(!ready(tasks).ready);}assert(F.validateTasks(changed(provisional(),t=>t.settings.unexpected=true),dataset,catalogue).some(e=>e.includes('unexpected')));});
test('structural provisional collection is ready while research remains unapproved',()=>{const t=provisional();assert.deepStrictEqual(F.validateTasks(t,dataset,catalogue),[]);assert.deepStrictEqual(ready(t),{ready:true,errors:[]});assert(!F.episodeReady(t,0,dataset,catalogue).ready);assert(F.validateTasks(t,dataset,catalogue,true).length);assert.strictEqual(t.settings.protocol_reviewed,false);assert.strictEqual(t.settings.hierarchy_reviewed,false);assert.strictEqual(t.layout.episodes[0].setup_reviewed,false);});
test('progress distinguishes collection readiness from research readiness',()=>{const p=F.progress(blank(),0,dataset,catalogue);assert.strictEqual(p.setup_ready,true);assert.strictEqual(p.collection_ready,true);assert.strictEqual(p.research_ready,false);assert.strictEqual(p.answered,0);});
test('each provisional scenario is answerable and visibly tagged provisional',()=>{const qs=F.questions(blank(),0,dataset,catalogue).filter(q=>['exposure','pathways'].includes(q.section));assert.strictEqual(qs.length,68);assert(qs.every(q=>q.blocked===false&&q.provisional===true&&q.direction.text));});
test('human answers remain null and no machine labels become human judgments',()=>{const d=blank();assert.strictEqual(d.benchmark_ready,false);for(const q of F.questions(d,0,dataset,catalogue))assert.strictEqual(F.get(d.episodes[0],q.path),null,q.path);assert.strictEqual(d.tasks.audits.sample.trajectory.valid,null);assert.strictEqual(d.tasks.audits.sample.glass.pane_present,null);});
test('provisional all answered scene and final export may complete without false approvals',()=>{const d=fill(blank());assert.deepStrictEqual(F.validateEpisode(d,0,dataset,catalogue,true),[]);assert.deepStrictEqual(F.validate(d,dataset,catalogue,true),[]);assert.strictEqual(d.tasks.settings.protocol_reviewed,false);assert.strictEqual(d.tasks.layout.episodes[0].setup_reviewed,false);assert.strictEqual(d.benchmark_ready,false);});
test('provisional completion still rejects missing answers and unexplained uncertainty',()=>{const d=fill(blank());d.episodes[0].checks.boundary.width_class=null;assert(F.validate(d,dataset,catalogue,true).some(e=>e.includes('width_class')));d.episodes[0].answers.notes='';assert(F.validate(d,dataset,catalogue,true).some(e=>e.includes('short explanation')));});
test('four targets per side required even when points_per_side is omitted',()=>{for(const side of ['indoor','exterior'])for(const n of [3,5]){const tasks=changed(provisional(),t=>{delete t.settings.points_per_side;const ep=t.layout.episodes[0];if(n===3)ep.markers.splice(ep.markers.findIndex(m=>m.side===side),1);else ep.markers.push({...C.clone(ep.markers.find(m=>m.side===side)),id:(side==='indoor'?'I':'E')+'5',x:.05});});assert(ready(tasks).errors.some(e=>e.includes('exactly 4')));assert(F.questions(blank(tasks),0,dataset,catalogue).filter(q=>q.section==='exposure').every(q=>q.blocked));}});
test('duplicate target coordinates cannot manufacture four distinct targets',()=>{const tasks=changed(provisional(),t=>{const [a,b]=t.layout.episodes[0].markers;b.x=a.x;b.y=a.y;});assert(ready(tasks).errors.some(e=>e.includes('duplicate red-point')));});
test('unknown frame, bad point coordinates and mismatched object categories rejected',()=>{for(const fn of [t=>t.layout.episodes[0].markers[0].anchor_frame='f99',t=>t.layout.episodes[0].markers[0].x=1.5,t=>t.layout.episodes[0].markers[0].mpcat40=8])assert(!ready(changed(provisional(),fn)).ready);});
test('exactly two valid distinct direction definitions required',()=>{for(const fn of [t=>t.layout.episodes[0].directions.pop(),t=>t.layout.episodes[0].directions[0].text='',t=>t.layout.episodes[0].directions[0].text='UNAPPROVED DRAFT: from [name the visible feature]',t=>t.layout.episodes[0].directions[0].x=null,t=>t.layout.episodes[0].directions[0].x=1.5,t=>t.layout.episodes[0].directions[0].reference_frame='f99',t=>t.layout.episodes[0].directions[0].id='d2',t=>t.layout.episodes[0].directions[0].text=t.layout.episodes[0].directions[1].text])assert(!ready(changed(provisional(),fn)).ready);});
test('two distinct valid indoor boundary witness boxes required',()=>{for(const fn of [t=>t.layout.episodes[0].boundary_boxes.pop(),t=>t.layout.episodes[0].boundary_boxes[1].frame_id='f07',t=>t.layout.episodes[0].boundary_boxes[1].frame_id='f01',t=>t.layout.episodes[0].boundary_boxes[0].x1=-1])assert(!ready(changed(provisional(),fn)).ready);});
test('shared coordinator, build, catalogue and hash invariants still enforced',()=>{for(const fn of [t=>t.coordinator='',t=>t.layout.coordinator='',t=>t.build_id='other',t=>t.settings.hierarchy_sha256='bad'])assert(!ready(changed(provisional(),fn)).ready);const stale=provisional();stale.layout.episodes[0].directions[0].text+=' changed';assert(ready(stale).errors.some(e=>e.includes('identity')||e.includes('hash')));assert(!F.episodeCollectionReady(provisional(),3,dataset,catalogue).ready);assert(!F.episodeCollectionReady(null,0,dataset,catalogue).ready);});
test('readiness cache detects in-place coordinates, direction edits and forged task identities',()=>{for(const fn of [t=>t.layout.episodes[0].markers[0].x=.13,t=>t.layout.episodes[0].directions[0].text+=' changed',t=>t.task_id='l2tasks-forged']){const t=provisional();assert(ready(t).ready);fn(t);assert(!ready(t).ready);}const t=provisional();assert(ready(t).ready);t.layout.episodes[0].directions[0].x=1.5;rehash(t);assert(!ready(t).ready);});
test('readiness cache detects dataset and catalogue mutations on the same objects',()=>{for(const fn of [d=>d.build_id='other',d=>d.episodes[0].frames[0].side='exterior',d=>{for(const f of d.episodes[0].frames)f.objects[0].mpcat40=8;}]){const d=C.clone(dataset),t=provisional();assert(F.episodeCollectionReady(t,0,d,catalogue).ready);fn(d);assert(!F.episodeCollectionReady(t,0,d,catalogue).ready);}for(const fn of [c=>c.build_id='other',c=>c.materials[0].name='Changed reference']){const c=C.clone(catalogue),t=provisional();assert(F.episodeCollectionReady(t,0,dataset,c).ready);fn(c);assert(!F.episodeCollectionReady(t,0,dataset,c).ready);}});
test('readiness cache cannot hide shared references or let callers mutate cached errors',()=>{const t=provisional();assert(ready(t).ready);t.layout.episodes[0].markers[1].observations=t.layout.episodes[0].markers[0].observations;assert(ready(t).errors.some(e=>e.includes('shared object')));const invalid=changed(provisional(),x=>x.layout.episodes[0].directions[0].x=1.5),first=ready(invalid);assert(first.errors.length);first.errors.length=0;assert(ready(invalid).errors.length);});
test('exclusion needs a shared reason and does not demand targets for excluded scene',()=>{const tasks=changed(provisional(),t=>{const ep=t.layout.episodes[0];ep.disposition='exclude';ep.markers=[];ep.directions=[];ep.boundary_boxes=[];});assert(!ready(tasks).ready);tasks.layout.episodes[0].exclusion_reason='No usable capture.';rehash(tasks);assert(ready(tasks).ready);});
test('consensus retains provisional known agreement but never marks it eligible GT',()=>{const a=fill(blank());a.episodes[0].answers.surfaces.I1.material='wood';a.episodes[0].checks.surfaces.I1.anchor_correct='yes';a.episodes[0].checks.surfaces.I1.same_surface_across_frames='yes';F.setAnswer(a,0,'checks.opening_passage.d1.open',['sunlight','rain','air','visible_light']);const b=C.clone(a);b.annotator='annotator-B';const report=F.consensus(a,b,dataset,catalogue),ep=report.episodes[0];assert.strictEqual(report.benchmark_ready,false);assert.strictEqual(ep.research_ready,false);assert(ep.research_setup_errors.length);assert.strictEqual(ep.fields['surfaces.I1.material'].state,'agreed');assert.strictEqual(ep.fields['surfaces.I1.material'].value,'wood');assert(Object.values(ep.fields).every(f=>f.eligible_known_gt===false&&f.eligible_nd_gt===false));assert.strictEqual(ep.fields['checks.opening_passage.d1.open'].eligible_consistency_check,true);assert.strictEqual(ep.drop_episode_known_gt,true);assert.strictEqual(ep.marker_readiness.I1.identity_certified,false);assert(Object.values(ep.family_annotation_coverage.A.exposure_sets).every(x=>!x.exact_set_labels_available));assert.strictEqual(ep.family_annotation_coverage.B.pathway_labels_available,false);assert.strictEqual(ep.family_annotation_coverage.B.rule_derivation.eligible_known_gt,false);assert(Object.values(ep.family_annotation_coverage.B.rule_derivation.scenarios).every(x=>!x.eligible_known_gt&&x.drop_item));assert.strictEqual(ep.family_annotation_coverage.D.class_comparison_gt_ready,false);});
test('provisional disagreement remains explicit and neither value wins',()=>{const a=fill(blank()),b=C.clone(a);b.annotator='annotator-B';a.episodes[0].answers.surfaces.I1.material='wood';b.episodes[0].answers.surfaces.I1.material='stone';const f=F.consensus(a,b,dataset,catalogue).episodes[0].fields['surfaces.I1.material'];assert.strictEqual(f.state,'disagreement');assert.strictEqual(f.value,null);assert.strictEqual(f.drop_known_gt,true);assert.strictEqual(f.rater_a,'wood');assert.strictEqual(f.rater_b,'stone');});
test('explicitly reviewed settings still work and do not make passage checks ground truth',()=>{const t=changed(provisional(),x=>{x.layout.episodes[0].setup_reviewed=true;Object.assign(x.settings,{protocol_reviewed:true,protocol_reviewer:'Reviewer',hierarchy_reviewed:true,hierarchy_reviewer:'Reviewer'});});assert(F.episodeReady(t,0,dataset,catalogue).ready);assert.deepStrictEqual(F.validateTasks(t,dataset,catalogue,true),[]);const a=fill(blank(t)),b=C.clone(a);a.episodes[0].answers.surfaces.I1.material='wood';b.episodes[0].answers.surfaces.I1.material='wood';b.annotator='annotator-B';const ep=F.consensus(a,b,dataset,catalogue).episodes[0];assert.strictEqual(ep.fields['surfaces.I1.material'].eligible_known_gt,true);assert.strictEqual(ep.fields['checks.opening_passage.d1.open'].eligible_known_gt,false);assert.strictEqual(ep.family_annotation_coverage.B.pathway_labels_available,false);});
test('claiming benchmark readiness remains a validation error',()=>{const d=fill(blank());d.benchmark_ready=true;assert(F.validate(d,dataset,catalogue,true).some(e=>e.includes('not benchmark ground truth')));});
test('unchanged provisional task migration preserves answers and reopens completion',()=>{const source=fill(blank());source.episodes[0].answers.surfaces.I1.material='wood';F.setAnswer(source,0,'answers.surfaces.I1.reachable.d1.open.sun','yes');F.setAnswer(source,0,'checks.opening_passage.d1.open',['sunlight']);const target=changed(source.tasks,t=>t.audits.sample.trajectory.notes='Additional machine provenance only.');const out=F.migrate(source,target,dataset,catalogue,'annotator-A');assert.strictEqual(out.doc.episodes[0].answers.surfaces.I1.material,'wood');assert.strictEqual(out.doc.episodes[0].answers.surfaces.I1.reachable.d1.open.sun,'yes');assert.deepStrictEqual(out.doc.episodes[0].checks.opening_passage.d1.open,['sunlight']);assert.strictEqual(out.doc.episodes[0].status,'in_progress');assert.strictEqual(out.doc.annotation_status,'draft');assert.strictEqual(out.doc.benchmark_ready,false);assert.strictEqual(out.doc.tasks.settings.protocol_reviewed,false);});
test('changed provisional direction text, anchors or protocol notes invalidate dependent votes',()=>{const source=blank();source.episodes[0].answers.surfaces.I1.material='wood';F.setAnswer(source,0,'answers.surfaces.I1.reachable.d1.open.sun','yes');F.setAnswer(source,0,'checks.opening_passage.d1.open',['sunlight']);for(const fn of [t=>t.layout.episodes[0].directions[0].text+=' Different path.',t=>t.layout.episodes[0].directions[0].x=.3,t=>t.settings.protocol_notes='Changed scenario semantics.']){const out=F.migrate(source,changed(source.tasks,fn),dataset,catalogue,'annotator-A').doc;assert.strictEqual(out.episodes[0].answers.surfaces.I1.material,'wood');assert.strictEqual(out.episodes[0].answers.surfaces.I1.reachable.d1.open.sun,'yes');assert.strictEqual(F.answerStatus(out,0,'answers.surfaces.I1.reachable.d1.open.sun').state,'needs_reanswer');assert.deepStrictEqual(out.episodes[0].checks.opening_passage.d1.open,['sunlight']);assert.strictEqual(F.answerStatus(out,0,'checks.opening_passage.d1.open').state,'needs_reanswer');}});
test('answers entered while old directions were blocked cannot migrate into active scenarios',()=>{const oldTasks=changed(provisional(),t=>delete t.settings.collection_mode),source=blank(oldTasks);F.setAnswer(source,0,'answers.surfaces.I1.reachable.d1.open.sun','yes');const target=changed(oldTasks,t=>t.settings.collection_mode='provisional'),out=F.migrate(source,target,dataset,catalogue,'annotator-A').doc;assert.strictEqual(out.episodes[0].answers.surfaces.I1.reachable.d1.open.sun,'yes');assert.strictEqual(F.answerStatus(out,0,'answers.surfaces.I1.reachable.d1.open.sun').state,'needs_reanswer');});
console.log(JSON.stringify({passed}));
