'use strict';
// Synthetic independent votes only; no real research approvals or human labels.
const assert=require('assert'),C=require('../core.js'),F=require('../full-core.js');
const dataset={build_id:'collection-checks-test',episodes:[{id:'synthetic-scene',frames:C.FRAMES.map((id,i)=>({id,side:i<6?'indoor':'exterior',boundary_pixels:150,boundary_bbox:[.1,.1,.6,.7],objects:[{object_id:1,mpcat40:3}]})),proposed_markers:['indoor','exterior'].flatMap(side=>[1,2,3,4].map(n=>({id:(side==='indoor'?'I':'E')+n,side,anchor_frame:side==='indoor'?'f01':'f07',x:n/5,y:.3,object_id:1,mpcat40:3,observations:[]})))}]};
const catalogue={build_id:dataset.build_id,materials:[{id:'wood',description:'Wood panel'}]};
const clone=C.clone,change=(doc,fn)=>{const d=clone(doc);fn(d);return d;};
const tasks=F.createTasks(dataset,catalogue,'Synthetic coordinator');
Object.assign(tasks.settings,{hierarchy_reviewed:true,hierarchy_reviewer:'Synthetic only',protocol_reviewed:true,protocol_reviewer:'Synthetic only',protocol_notes:'Synthetic fixture, not research settings'});
tasks.layout.episodes[0].setup_reviewed=true;
tasks.layout.episodes[0].directions=[{id:'d1',text:'From the visible left tree toward the door',reference_frame:'f07',x:.2,y:.5},{id:'d2',text:'From the visible right wall toward the door',reference_frame:'f07',x:.8,y:.5}];
tasks.layout.layout_id=C.layoutId(tasks.layout);tasks.task_id=F.taskId(tasks);
const draft=F.create(dataset,catalogue,tasks,'Synthetic rater A');
function fill(source){const d=clone(source);for(const q of F.questions(d,0,dataset,catalogue))F.set(d.episodes[0],q.path,q.kind==='multiselect'?[C.ND]:C.ND);d.episodes[0].answers.notes='Synthetic uncertainty';d.episodes[0].status='complete';d.episodes[0].completed_at=new Date().toISOString();d.annotation_status='complete';return d;}
const complete=fill(draft);
const old=source=>change(source,d=>{delete d.collection_checks_version;for(const r of d.episodes){delete r.checks.opening_passage;delete r.checks.indoor_visibility;}});
const legacyComplete=fill(old(draft));
const pair=(first,second=change(first,d=>d.annotator='Synthetic rater B'))=>F.consensus(first,second,dataset,catalogue);
function known(){const d=clone(complete),r=d.episodes[0];Object.assign(r.answers.scene,{crossing_valid:'yes',canonical_context_clear:'yes',boundary_class:'outdoor'});Object.assign(r.checks,{indoor_region_correct:'yes',exterior_region_correct:'yes'});Object.assign(r.answers.boundary,{object_identity_correct:'yes',kind:'door',observed_state:'closed',material:'glass',pane_transparency:'clear',glazing:'present',air_gap:'no'});r.checks.boundary.blockage='none';for(const f of ['f01','f02'])Object.assign(r.answers.boundary_visibility[f],{visibility:'direct',object_match:'yes',box_correct:'yes'});for(const m of d.tasks.layout.episodes[0].markers)Object.assign(r.checks.surfaces[m.id],{anchor_correct:'yes',same_surface_across_frames:'yes'});for(const dir of C.DIRECTIONS){r.checks.opening_passage[dir].open=['sunlight','rain','air','visible_light'];r.checks.opening_passage[dir].sealed=['sunlight','visible_light'];}for(const id of Object.keys(r.checks.indoor_visibility))r.checks.indoor_visibility[id]=['f07','f09'];return d;}
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}

test('fresh records add explicit scope and blank independent human checklists',()=>{assert.equal(draft.collection_checks_version,1);assert.deepStrictEqual(draft.episodes[0].checks.opening_passage,{d1:{open:null,sealed:null},d2:{open:null,sealed:null}});assert.deepStrictEqual(draft.episodes[0].checks.indoor_visibility,{I1:null,I2:null,I3:null,I4:null});assert.deepStrictEqual(F.validate(draft,dataset,catalogue),[]);});
test('exactly four scenario questions replace sixteen scalar passage questions',()=>{const qs=F.questions(draft,0,dataset,catalogue),pass=qs.filter(q=>q.section==='pathways');assert.equal(pass.length,4);for(const q of pass){assert.equal(q.kind,'multiselect');assert(q.consistency_only);assert(q.direction.text&&q.condition_text);assert.deepStrictEqual(q.options.map(o=>o.value),['sunlight','rain','air','visible_light','none',C.ND]);}assert(!qs.some(q=>q.path.startsWith('answers.pathways.')));assert.equal(F.questions(old(draft),0,dataset,catalogue).filter(q=>q.section==='pathways').length,16);});
test('one indoor-point visibility question uses only exterior images, without replacing door checks',()=>{const qs=F.questions(draft,0,dataset,catalogue),v=qs.filter(q=>q.path.startsWith('checks.indoor_visibility.'));assert.equal(v.length,4);assert.equal(qs.filter(q=>q.path.startsWith('answers.boundary_visibility.')).length,6);for(const q of v){assert.deepStrictEqual(q.options.map(o=>o.value),['f07','f08','f09','f10','f11','f12','none',C.ND]);assert(q.help.includes('through glass'));assert(q.help.includes('reflection'));assert(q.help.includes('missing red-point projection'));}});
test('L2+3 keeps detailed per-frame visibility plus the same four indoor recall checks',()=>{const d=change(draft,x=>x.profile='l2_l3'),qs=F.questions(d,0,dataset,catalogue);assert.equal(qs.filter(q=>q.path.startsWith('checks.indoor_visibility.')).length,4);assert.equal(qs.filter(q=>/^answers\.surfaces\.[^.]+\.visibility\./.test(q.path)).length,96);});
test('canonical ordering is deterministic and independent of checkbox click order',()=>{assert.deepStrictEqual(F.canonicalSelections(['air','sunlight'],F.PASSAGE_OPTIONS),['sunlight','air']);const q=F.questions(draft,0,dataset,catalogue).find(q=>q.kind==='multiselect');assert.deepStrictEqual(F.canonicalSelections(['visible_light','rain'],q.options),['rain','visible_light']);});
test('empty, duplicate, unknown, unordered, and mixed special selections are rejected',()=>{for(const value of [[],['sunlight','sunlight'],['unknown'],['air','sunlight'],['none','rain'],[C.ND,'air'],'none',{},false])assert(F.validate(change(draft,d=>d.episodes[0].checks.opening_passage.d1.open=value),dataset,catalogue).length,JSON.stringify(value));for(const value of [['f01'],['f12','f07'],['none','f07'],['f07','f07'],[]])assert(F.validate(change(draft,d=>d.episodes[0].checks.indoor_visibility.I1=value),dataset,catalogue).length);});
test('ordinary and exclusive special choices are valid without machine defaults',()=>{for(const value of [['sunlight'],['rain','air'],['none'],[C.ND],null])assert.deepStrictEqual(F.validate(change(draft,d=>d.episodes[0].checks.opening_passage.d1.open=value),dataset,catalogue),[]);for(const value of [['f07','f12'],['none'],[C.ND],null])assert.deepStrictEqual(F.validate(change(draft,d=>d.episodes[0].checks.indoor_visibility.I1=value),dataset,catalogue),[]);});
test('complete exports require every checklist and explicit ND still requires a note',()=>{assert.deepStrictEqual(F.validate(complete,dataset,catalogue,true),[]);for(const path of ['checks.opening_passage.d1.open','checks.indoor_visibility.I4'])assert(F.validate(change(complete,d=>F.set(d.episodes[0],path,null)),dataset,catalogue,true).some(e=>e.includes(path)));assert(F.validate(change(complete,d=>d.episodes[0].answers.notes=''),dataset,catalogue,true).some(e=>e.includes('short explanation')));});
test('legacy exports remain valid under their original scope without extension masquerading',()=>{assert.deepStrictEqual(F.validate(legacyComplete,dataset,catalogue,true),[]);assert(F.needsCollectionUpgrade(legacyComplete));for(const version of [null,0,2,'1'])assert(F.validate(change(draft,d=>d.collection_checks_version=version),dataset,catalogue).length);assert(F.validate(change(draft,d=>delete d.collection_checks_version),dataset,catalogue).length);assert(F.validate(change(draft,d=>delete d.episodes[0].checks.indoor_visibility),dataset,catalogue).length);});
test('upgrade preserves all old raw answers, identity, notes and source provenance',()=>{const source=change(legacyComplete,d=>{d.episodes[0].answers.pathways.d1.open.air='yes';d.episodes[0].answers.surfaces.I1.visibility.f07='direct';}),before=clone(source),out=F.upgradeCollection(source,dataset,catalogue);assert.deepStrictEqual(source,before);assert.deepStrictEqual(out.doc.episodes[0].answers,source.episodes[0].answers);assert.equal(out.doc.task_id,source.task_id);assert.deepStrictEqual(out.doc.tasks,source.tasks);assert.equal(out.doc.episodes[0].checks.indoor_visibility.I1,null);assert.equal(out.doc.episodes[0].checks.opening_passage.d1.open,null);assert.equal(out.report.added_questions,8);assert.equal(out.report.replaced_questions,16);assert.equal(out.doc.migration_log.at(-1).source_sha256,C.sha256(C.stableStringify(source)));assert.equal(out.doc.migration_log.at(-1).source_episode_statuses[0].completed_at,source.episodes[0].completed_at);});
test('upgrade reopens only included completed scenes and is idempotent',()=>{const out=F.upgradeCollection(legacyComplete,dataset,catalogue);assert.equal(out.doc.annotation_status,'draft');assert.equal(out.doc.episodes[0].status,'in_progress');assert.equal(out.doc.episodes[0].completed_at,null);assert.equal(F.progress(out.doc,0,dataset,catalogue).missing.length,8);assert.deepStrictEqual(F.validate(out.doc,dataset,catalogue),[]);assert.deepStrictEqual(F.upgradeCollection(out.doc,dataset,catalogue).doc,out.doc);const excluded=change(legacyComplete,d=>{d.episodes[0].status='excluded';d.episodes[0].exclusion_reason='Synthetic excluded target';}),e=F.upgradeCollection(excluded,dataset,catalogue);assert.equal(e.doc.episodes[0].status,'excluded');assert.equal(e.doc.annotation_status,'complete');assert.equal(e.report.added_questions,0);assert.deepStrictEqual(F.validate(e.doc,dataset,catalogue,true),[]);});
test('foreign-rater or malformed upgrades and mixed-version consensus are rejected',()=>{assert.throws(()=>F.upgradeCollection(legacyComplete,dataset,catalogue,'Someone else'),/own annotation/);assert.throws(()=>F.upgradeCollection(change(legacyComplete,d=>d.episodes[0].answers.boundary.kind='bad'),dataset,catalogue),/invalid value/);assert.throws(()=>pair(legacyComplete,change(complete,d=>d.annotator='Synthetic rater B')),/same collection checks version/);});
test('same-task migration preserves checks but changed directions clear only passage checks',()=>{const src=known(),same=F.migrate(src,tasks,dataset,catalogue,src.annotator).doc;assert.deepStrictEqual(same.episodes[0].checks.opening_passage,src.episodes[0].checks.opening_passage);assert.deepStrictEqual(same.episodes[0].checks.indoor_visibility,src.episodes[0].checks.indoor_visibility);const t=change(tasks,t=>{t.layout.episodes[0].directions[0].text+=' revised';t.layout.layout_id='';t.task_id=F.taskId(t);}),out=F.migrate(src,t,dataset,catalogue,src.annotator).doc;assert.equal(out.episodes[0].checks.opening_passage.d1.open,null);assert.deepStrictEqual(out.episodes[0].checks.indoor_visibility.I1,['f07','f09']);});
test('moved or correspondence-changed indoor targets cannot inherit visibility',()=>{const src=known();for(const edit of [m=>m.x=.11,m=>m.observations.push({frame_id:'f07',x:.3,y:.4,source:'human'})]){const t=change(tasks,t=>{edit(t.layout.episodes[0].markers[0]);t.layout.layout_id='';t.task_id=F.taskId(t);}),out=F.migrate(src,t,dataset,catalogue,src.annotator).doc;assert.equal(out.episodes[0].checks.indoor_visibility.I1,null);assert.deepStrictEqual(out.episodes[0].checks.indoor_visibility.I2,['f07','f09']);}});
test('changed boundary clears directional consistency checks but retains same surface recall votes',()=>{const src=known(),t=change(tasks,t=>{t.layout.episodes[0].boundary_boxes[0].x0=.05;t.layout.layout_id='';t.task_id=F.taskId(t);}),out=F.migrate(src,t,dataset,catalogue,src.annotator).doc;assert.equal(out.episodes[0].checks.opening_passage.d1.open,null);assert.deepStrictEqual(out.episodes[0].checks.indoor_visibility.I1,['f07','f09']);});
test('equal arrays form exact independent agreement and retain raw votes',()=>{const r=pair(known()),f=r.episodes[0].fields['checks.indoor_visibility.I1'];assert.equal(f.state,'agreed');assert.deepStrictEqual(f.value,['f07','f09']);assert.deepStrictEqual(f.rater_a,f.rater_b);assert.equal(r.agreement_by_attribute['checks.indoor_visibility.*'].n_agreed,4);assert.equal(r.agreement_by_attribute['checks.indoor_visibility.*'].observed_agreement,1);});
test('ND arrays remain uncertainty, never an empty visible set or Nothing',()=>{const r=pair(complete),v=r.episodes[0].fields['checks.indoor_visibility.I1'];assert.equal(v.state,'agreed_not_determinable');assert.deepStrictEqual(v.value,[C.ND]);assert(!v.eligible_known_gt);assert.equal(r.agreement_by_attribute['checks.indoor_visibility.*'].n_agreed_nd,4);assert.equal(r.agreement_by_attribute['checks.indoor_visibility.*'].n_known_compared,0);});
test('visibility disagreements drop only the affected point, keeping agreed other points',()=>{const a=known(),b=change(a,d=>{d.annotator='Synthetic rater B';d.episodes[0].checks.indoor_visibility.I1=['f08'];}),e=pair(a,b).episodes[0];assert(!e.drop_episode_known_gt);assert.equal(e.fields['checks.indoor_visibility.I1'].state,'disagreement');assert(!e.indoor_visibility_coverage.I1.eligible_known_gt);assert(e.indoor_visibility_coverage.I1.drop_item);assert(e.indoor_visibility_coverage.I2.eligible_known_gt);assert.deepStrictEqual(e.indoor_visibility_coverage.I2.visible_after_crossing_frames,['f07','f09']);assert.deepStrictEqual(e.disagreements.find(x=>x.path==='checks.indoor_visibility.I1').rater_b,['f08']);});
test('explicit None is a certified empty set only with agreed scene and target identity',()=>{const a=change(known(),d=>d.episodes[0].checks.indoor_visibility.I1=['none']);let e=pair(a).episodes[0];assert(e.indoor_visibility_coverage.I1.eligible_known_gt);assert.deepStrictEqual(e.indoor_visibility_coverage.I1.visible_after_crossing_frames,[]);a.episodes[0].checks.surfaces.I1.anchor_correct='no';e=pair(a).episodes[0];assert(!e.indoor_visibility_coverage.I1.eligible_known_gt);assert.equal(e.indoor_visibility_coverage.I1.visible_after_crossing_frames,null);});
test('new and legacy passage votes are consistency data and can never be benchmark GT',()=>{for(const source of [known(),change(legacyComplete,d=>d.episodes[0].answers.pathways.d1.open.air='yes')]){const e=pair(source).episodes[0],p=source.collection_checks_version?'checks.opening_passage.d1.open':'pathways.d1.open.air';assert(e.fields[p].consistency_only);assert(!e.fields[p].eligible_known_gt);assert(!e.fields[p].eligible_nd_gt);assert(!e.family_annotation_coverage.B.pathway_labels_available);assert(!e.family_annotation_coverage.B.human_passage_votes_are_gt);}});
test('rule candidates derive from agreed facts separately, retain pending approval and never enable GT',()=>{const e=pair(known()).episodes[0],rule=e.family_annotation_coverage.B.rule_derivation;assert.equal(rule.rule_status,'pending_review');assert(!rule.eligible_known_gt);assert.deepStrictEqual(rule.scenarios['d1.sealed'].candidate_selection,['sunlight','visible_light']);assert.equal(rule.scenarios['d1.sealed'].candidate_channels.rain.candidate_value,'no');assert.equal(rule.scenarios['d1.sealed'].consistency_status,'matches_rule_candidate');assert(rule.scenarios['d1.sealed'].drop_item);assert(rule.scenarios['d1.sealed'].candidate_channels.sunlight.source_paths.includes('boundary.pane_transparency'));assert(!rule.scenarios['d1.sealed'].eligible_known_gt);});
test('different passage check votes drop their scenario, without deriving answers from either vote',()=>{const a=known(),b=change(a,d=>{d.annotator='Synthetic rater B';d.episodes[0].checks.opening_passage.d1.open=['air'];}),e=pair(a,b).episodes[0],s=e.family_annotation_coverage.B.rule_derivation.scenarios;assert.equal(s['d1.open'].consistency_status,'rater_disagreement');assert(s['d1.open'].drop_due_to_consistency_check);assert.equal(s['d2.open'].consistency_status,'matches_rule_candidate');assert(!s['d2.open'].drop_due_to_consistency_check);assert(!e.drop_episode_known_gt);assert.equal(s['d1.open'].candidate_channels.rain.candidate_value,'yes');});
test('agreed checks conflicting with sealed physics are flagged, never corrected',()=>{const a=change(known(),d=>d.episodes[0].checks.opening_passage.d1.sealed=['air']),e=pair(a).episodes[0],s=e.family_annotation_coverage.B.rule_derivation.scenarios['d1.sealed'];assert.equal(s.consistency_status,'conflict_with_rule_candidate');assert(s.conflicting_channels.includes('air'));assert(s.drop_due_to_consistency_check);assert.deepStrictEqual(e.fields['checks.opening_passage.d1.sealed'].value,['air']);assert(e.family_annotation_coverage.B.consistency_review_required);});
test('uncertain or disputed primary facts do not become rule inputs and do not discard unrelated answers',()=>{const a=known(),b=change(a,d=>{d.annotator='Synthetic rater B';d.episodes[0].answers.boundary.pane_transparency='opaque';}),e=pair(a,b).episodes[0],s=e.family_annotation_coverage.B.rule_derivation.scenarios['d1.sealed'];assert.equal(s.candidate_channels.sunlight.candidate_value,C.ND);assert(s.candidate_channels.sunlight.blocked_fields.includes('boundary.pane_transparency'));assert.equal(s.candidate_channels.rain.candidate_value,'no');assert(e.indoor_visibility_coverage.I1.eligible_known_gt);assert(!e.drop_episode_known_gt);});
test('obscured panes, blockers and nonexistent closures remain unresolved where facts are insufficient',()=>{for(const mutate of [d=>d.episodes[0].answers.boundary.pane_transparency='obscured',d=>d.episodes[0].checks.boundary.blockage='curtains',d=>Object.assign(d.episodes[0].answers.boundary,{kind:'open_passage',observed_state:'no_closure'})]){const a=change(known(),mutate),s=pair(a).episodes[0].family_annotation_coverage.B.rule_derivation.scenarios['d1.sealed'];assert.equal(s.candidate_channels.sunlight.candidate_value,C.ND);assert(!s.eligible_known_gt);}});
test('no direct adjudication or same-rater consensus can overwrite independent facts',()=>{assert.throws(()=>F.consensus(complete,complete,dataset,catalogue),/distinct independent/);assert(!Object.hasOwn(F,'resolveDisagreement'));assert(pair(known()).policy.includes('no adjudication'));});
console.log(JSON.stringify({passed}));
