'use strict';
// Synthetic independent-rater fixtures only. No real human labels are changed.
const assert=require('assert'),C=require('../core.js'),F=require('../full-core.js');
const dataset={build_id:'direction-provenance-test',episodes:['one','two'].map(id=>({id,frames:C.FRAMES.map((id,i)=>({id,side:i<6?'indoor':'exterior',boundary_pixels:150,boundary_bbox:[.1,.1,.6,.8],objects:[{object_id:1,mpcat40:3}]})),proposed_markers:['indoor','exterior'].flatMap(side=>[1,2,3,4].map(n=>({id:(side==='indoor'?'I':'E')+n,side,anchor_frame:side==='indoor'?'f01':'f07',x:n/5,y:.4,object_id:1,mpcat40:3,observations:[]})))}))};
const catalogue={build_id:dataset.build_id,materials:[{id:'wood',name:'Wood'}]};
const P='answers.surfaces.I1.reachable.d1.open.sun',D2=P.replace('.d1.','.d2.'),RAIN=P.replace('.sun','.rain'),CHECK='checks.opening_passage.d1.open',OLD='answers.pathways.d1.open.air';
function rehash(t){t.layout.layout_id=C.layoutId(t.layout);t.task_id=F.taskId(t);return t;}
function tasks(){const t=F.createTasks(dataset,catalogue,'Synthetic coordinator');Object.assign(t.settings,{collection_mode:'provisional',points_per_side:4});for(const ep of t.layout.episodes)ep.directions=[{id:'d1',text:'From directly above the exterior side of the opening.',reference_frame:'f06',x:.2,y:.3},{id:'d2',text:'Sideways from the open exterior side through the opening.',reference_frame:'f06',x:.4,y:.5}];return rehash(t);}
function blank(){return F.create(dataset,catalogue,tasks(),'A');}
function changed(source,fn){const t=C.clone(source.tasks);fn(t);return rehash(t);}
function answered(){const d=blank();for(let i=0;i<d.episodes.length;i++)for(const [p,v]of [[P,'yes'],[D2,'no'],[RAIN,'no'],[CHECK,['sunlight']],[OLD,'yes']])F.setAnswer(d,i,p,v);return d;}
function fill(d=blank()){for(let i=0;i<d.episodes.length;i++){for(const q of F.questions(d,i,dataset,catalogue))F.setAnswer(d,i,q.path,q.kind==='multiselect'?[C.ND]:C.ND);d.episodes[i].answers.notes='Synthetic uncertainty for regression tests.';d.episodes[i].status='complete';d.episodes[i].completed_at=new Date().toISOString();}d.annotation_status='complete';return d;}
function migrate(d,fn){return F.migrate(d,changed(d,fn),dataset,catalogue,'A');}
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('new exports start strict, empty and with truthful zero elapsed time',()=>{const d=blank();assert.strictEqual(d.answer_provenance_version,1);assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);assert.deepStrictEqual(d.episodes[0].answer_provenance,{});assert.deepStrictEqual(d.episodes[0].direction_versions,{});assert.strictEqual(d.episodes[0].time_tracking.active_ms,0);assert.strictEqual(d.episodes[0].time_tracking.prior_time_unavailable,false);});
test('per-answer stamp resolves exact direction, task identity and timestamp',()=>{const d=answered(),s=F.answerStatus(d,0,P);assert.strictEqual(s.state,'current');assert.strictEqual(s.saved_context.direction.text,d.tasks.layout.episodes[0].directions[0].text);assert.strictEqual(s.task_id,d.task_id);assert(/^[a-f0-9]{64}$/.test(s.dependency_sha256));assert.strictEqual(s.provenance.value,'yes');assert(s.provenance.recorded_at);assert.strictEqual(Object.keys(d.episodes[0].direction_versions).length,1);assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('unstamped modern votes never count as current',()=>{const d=blank();F.set(d.episodes[0],P,'yes');assert.strictEqual(F.answerStatus(d,0,P).state,'needs_reanswer');assert.strictEqual(F.progress(d,0,dataset,catalogue).answered,0);assert(F.validateEpisode(d,0,dataset,catalogue,true).some(x=>x.includes('needs redoing')));});
test('edits bypassing setAnswer cannot reuse another value provenance',()=>{const d=answered();F.set(d.episodes[0],P,'no');assert.strictEqual(F.answerStatus(d,0,P).state,'needs_reanswer');});
test('one direction edit invalidates that direction only and preserves old values',()=>{const source=answered(),out=migrate(source,t=>t.layout.episodes[0].directions[0].text+=' Changed path.');assert.strictEqual(F.get(out.doc.episodes[0],P),'yes');for(const path of [P,RAIN,CHECK,OLD])assert.strictEqual(F.answerStatus(out.doc,0,path).state,'needs_reanswer');assert.strictEqual(F.answerStatus(out.doc,0,D2).state,'current');assert.strictEqual(F.answerStatus(out.doc,1,P).state,'current');assert.strictEqual(out.report.needs_reanswer,4);assert.strictEqual(out.doc.episodes[0].answer_provenance[P].state,'needs_reanswer');assert.strictEqual(F.answerStatus(out.doc,0,P).task_id,source.task_id);assert.deepStrictEqual(F.validate(out.doc,dataset,catalogue),[]);});
test('direction anchor coordinates and reference frame are dependencies',()=>{for(const fn of [t=>t.layout.episodes[0].directions[0].x=.25,t=>t.layout.episodes[0].directions[0].reference_frame='f05']){const d=migrate(answered(),fn).doc;assert.strictEqual(F.answerStatus(d,0,P).state,'needs_reanswer');assert.strictEqual(F.answerStatus(d,0,D2).state,'current');}});
test('protocol notes invalidate every dependent direction without altering raw votes',()=>{const d=migrate(answered(),t=>t.settings.protocol_notes='New scenario instruction.').doc;for(const path of [P,D2,CHECK,OLD])assert.strictEqual(F.answerStatus(d,0,path).state,'needs_reanswer');});
test('target geometry invalidates only that target exposure, not opening checklist',()=>{const d=migrate(answered(),t=>t.layout.episodes[0].markers[0].x=.15).doc;assert.strictEqual(F.answerStatus(d,0,P).state,'needs_reanswer');assert.strictEqual(F.answerStatus(d,0,D2).state,'needs_reanswer');assert.strictEqual(F.answerStatus(d,0,CHECK).state,'current');});
test('changed boundary geometry invalidates exposure and opening checklist',()=>{const d=migrate(answered(),t=>t.layout.episodes[0].boundary_boxes[0].x1=.11).doc;assert.strictEqual(F.answerStatus(d,0,P).state,'needs_reanswer');assert.strictEqual(F.answerStatus(d,0,CHECK).state,'needs_reanswer');});
test('unrelated audit notes retain direction stamps with original task ID',()=>{const source=answered(),d=migrate(source,t=>t.audits.one.trajectory.notes='Additional non-semantic provenance.').doc;assert.notStrictEqual(d.task_id,source.task_id);assert.strictEqual(F.answerStatus(d,0,P).state,'current');assert.strictEqual(F.answerStatus(d,0,P).task_id,source.task_id);assert.deepStrictEqual(d.episodes[0].answer_provenance[P],source.episodes[0].answer_provenance[P]);});
test('read-only published-task audit identifies stale answers without modifying source',()=>{const d=answered(),before=C.stableStringify(d),published=changed(d,t=>t.layout.episodes[0].directions[0].text+=' Different.');assert.strictEqual(F.answerStatus(d,0,P,published).state,'needs_reanswer');assert.strictEqual(F.answerStatus(d,0,D2,published).state,'current');assert.strictEqual(C.stableStringify(d),before);});
test('reconciliation reopens completed scene and final export',()=>{const d=fill();d.tasks=changed(d,t=>t.layout.episodes[0].directions[0].text+=' Different.');d.task_id=d.tasks.task_id;const report=F.reconcileProvenance(d);assert.strictEqual(report.needs_reanswer,34);assert.deepStrictEqual(report.reopened_episodes,['one']);assert.strictEqual(d.episodes[0].status,'in_progress');assert.strictEqual(d.episodes[0].completed_at,null);assert.strictEqual(d.episodes[1].status,'complete');assert.strictEqual(d.annotation_status,'draft');assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('re-answering explicitly preserves old value and exact direction revision',()=>{const source=answered(),d=migrate(source,t=>t.layout.episodes[0].directions[0].text+=' New direction.').doc;F.setAnswer(d,0,P,'no');const current=F.answerStatus(d,0,P),entry=d.episodes[0].answer_provenance[P];assert.strictEqual(current.state,'current');assert.strictEqual(current.task_id,d.task_id);assert.strictEqual(entry.history.length,1);assert.strictEqual(entry.history[0].value,'yes');assert.strictEqual(entry.history[0].state,'needs_reanswer');assert.notStrictEqual(entry.revision,entry.history[0].revision);assert.strictEqual(d.episodes[0].direction_versions[entry.history[0].revision].task_id,source.task_id);assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('re-answering same value is explicit confirmation, not auto-clearing stale flag',()=>{const d=migrate(answered(),t=>t.layout.episodes[0].directions[0].text+=' New direction.').doc;F.setAnswer(d,0,P,'yes');assert.strictEqual(F.answerStatus(d,0,P).state,'current');assert.strictEqual(d.episodes[0].answer_provenance[P].history[0].value,'yes');});
test('legacy documents are upgraded from embedded tasks without invented answer times',()=>{const d=answered();delete d.answer_provenance_version;for(const r of d.episodes){delete r.answer_provenance;delete r.direction_versions;delete r.time_tracking;}const before=C.stableStringify(d),out=F.upgradeProvenance(d,dataset,catalogue,'A');assert(out.report.upgraded);assert.strictEqual(out.report.inferred_answers,10);assert.strictEqual(out.doc.episodes[0].answer_provenance[P].origin,'inferred_from_embedded_task');assert.strictEqual(out.doc.episodes[0].answer_provenance[P].recorded_at,null);assert.strictEqual(out.doc.episodes[0].time_tracking.prior_time_unavailable,true);assert.strictEqual(C.stableStringify(d),before);assert.strictEqual(F.answerStatus(out.doc,0,P).state,'current');assert.deepStrictEqual(F.validate(out.doc,dataset,catalogue),[]);});
test('legacy read-only comparison reports inference honestly and changed direction stale',()=>{const d=answered();delete d.answer_provenance_version;for(const r of d.episodes){delete r.answer_provenance;delete r.direction_versions;}assert.strictEqual(F.answerStatus(d,0,P).legacy_inferred,true);const published=changed(d,t=>t.layout.episodes[0].directions[0].text+=' Change.');assert.strictEqual(F.answerStatus(d,0,P,published).state,'needs_reanswer');});
test('modern missing provenance is not blessed by migration',()=>{const d=blank();F.set(d.episodes[0],P,'yes');const out=migrate(d,t=>t.audits.one.trajectory.notes='Irrelevant').doc;assert.strictEqual(F.answerStatus(out,0,P).state,'needs_reanswer');assert.strictEqual(out.episodes[0].answer_provenance[P],undefined);});
test('removing document version cannot recertify modern stale provenance as legacy',()=>{const d=migrate(answered(),t=>t.layout.episodes[0].directions[0].text+=' New direction.').doc;delete d.answer_provenance_version;assert(F.validate(d,dataset,catalogue).some(x=>x.includes('requires its document version')));assert.throws(()=>F.upgradeProvenance(d,dataset,catalogue,'A'),/requires its document version/);});
test('own-ID import restriction remains enforced for upgrades and migrations',()=>{const d=answered();assert.throws(()=>F.upgradeProvenance(d,dataset,catalogue,'B'),/own annotation/);assert.throws(()=>F.migrate(d,d.tasks,dataset,catalogue,'B'),/own annotation/);});
test('invalid snapshot hash and dangling revision are rejected',()=>{const d=answered(),r=d.episodes[0];r.direction_versions.r1.snapshot.directions[0].text='Tampered';assert(F.validate(d,dataset,catalogue).some(x=>x.includes('snapshot hash mismatch')));assert.strictEqual(F.answerStatus(d,0,P).state,'needs_reanswer');const other=answered();other.episodes[0].answer_provenance[P].revision='r999';assert(F.validate(other,dataset,catalogue).some(x=>x.includes('version unavailable')));});
test('hash-consistent malformed snapshot structures are rejected safely',()=>{for(const change of [s=>s.directions=[null,null],s=>s.directions[0].text=42,s=>s.conditions={},s=>s.protocol={}]){const d=answered(),v=d.episodes[0].direction_versions.r1;change(v.snapshot);v.snapshot_sha256=C.sha256(C.stableStringify(v.snapshot));assert(F.validate(d,dataset,catalogue).length);assert.doesNotThrow(()=>F.answerStatus(d,0,P));}});
test('selected condition alone is a read-only dependency rather than unrelated scenario wording',()=>{const d=answered();F.setAnswer(d,0,P.replace('.open.','.sealed.'),'no');const published=C.clone(d.tasks);published.layout.conditions.open+=' Additional instruction.';assert.strictEqual(F.answerStatus(d,0,P,published).state,'needs_reanswer');assert.strictEqual(F.answerStatus(d,0,P.replace('.open.','.sealed.'),published).state,'current');});
test('time metadata survives migration and invalid elapsed values are rejected',()=>{const d=answered(),at=new Date().toISOString();d.episodes[0].time_tracking={version:1,active_ms:2400,first_started_at:at,last_active_at:at,tracking_started_at:at,prior_time_unavailable:false};const out=migrate(d,t=>t.audits.one.trajectory.notes='Notes').doc;assert.deepStrictEqual(out.episodes[0].time_tracking,d.episodes[0].time_tracking);assert.deepStrictEqual(F.validate(out,dataset,catalogue),[]);out.episodes[0].time_tracking.active_ms=-1;assert(F.validate(out,dataset,catalogue).some(x=>x.includes('invalid timing')));});
test('fully completed current-direction exports still validate',()=>assert.deepStrictEqual(F.validate(fill(),dataset,catalogue,true),[]));
test('stale votes cannot enter consensus or become benchmark GT',()=>{const a=fill(),b=C.clone(a);b.annotator='B';a.tasks=changed(a,t=>t.layout.episodes[0].directions[0].text+=' Changed.');a.task_id=a.tasks.task_id;assert.throws(()=>F.consensus(a,b,dataset,catalogue),/needs redoing/);});
test('all three directional answer families are discoverable, not ordinary material fields',()=>{const d=answered(),paths=F.directionalPaths(d,0);for(const path of [P,D2,RAIN,CHECK,OLD])assert(paths.includes(path));assert.strictEqual(paths.length,84);assert.strictEqual(F.answerStatus(d,0,'answers.surfaces.I1.material').state,'not_directional');assert.strictEqual(F.answerStatus(blank(),0,P).state,'unanswered');});
test('clearing a directional answer keeps a versioned history but remains unanswered',()=>{const d=answered();F.setAnswer(d,0,P,null);assert.strictEqual(F.answerStatus(d,0,P).state,'unanswered');assert.strictEqual(d.episodes[0].answer_provenance[P].history[0].value,'yes');assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('setAnswer rejects unsafe or missing paths without corrupting provenance',()=>{const d=answered(),before=C.stableStringify(d);assert.throws(()=>F.setAnswer(d,0,'answers.__proto__.test','yes'),/Unsafe/);assert.throws(()=>F.setAnswer(d,0,'answers.surfaces.I9.reachable.d1.open.sun','yes'),/Unknown/);assert.strictEqual(C.stableStringify(d),before);});
console.log(JSON.stringify({passed}));
