'use strict';
const assert=require('assert'),crypto=require('crypto'),C=require('../core.js'),F=require('../full-core.js'),G=require('../guided-core.js');
const fixtureOnly=process.argv.includes('--fixture');
const dataset={build_id:'full-unit-test',episodes:[{id:'unit-episode',frames:C.FRAMES.map((id,i)=>({id,side:i<6?'indoor':'exterior',boundary_pixels:150,boundary_bbox:[.1,.1,.6,.7],objects:[{object_id:1,mpcat40:3},{object_id:2,mpcat40:3}]})),proposed_markers:['indoor','exterior'].flatMap(side=>[1,2,3].map(n=>({id:(side==='indoor'?'I':'E')+n,side,anchor_frame:side==='indoor'?'f01':'f07',x:n/4,y:.3,object_id:1,mpcat40:3,observations:[]})))}]};
const catalogue={build_id:dataset.build_id,materials:[{id:'wood',name:'Wood panel',description:'Wooden installed panel'}]};
function approved(){const t=F.createTasks(dataset,catalogue,'Researcher');const ep=t.layout.episodes[0];ep.setup_reviewed=true;ep.directions=[{id:'d1',text:'From the tree on the left toward the marked door',reference_frame:'f07',x:.2,y:.5},{id:'d2',text:'From the wall on the right toward the marked door',reference_frame:'f07',x:.8,y:.5}];Object.assign(t.settings,{hierarchy_reviewed:true,hierarchy_reviewer:'Researcher',protocol_reviewed:true,protocol_reviewer:'Researcher',protocol_notes:'Synthetic test settings only.'});t.layout.layout_id=C.layoutId(t.layout);t.task_id=F.taskId(t);return t;}
function changed(v,fn){const out=C.clone(v);fn(out);return out;}
function rehash(t){t.layout.layout_id='';t.task_id=F.taskId(t);return t;}
function fill(doc){for(const q of F.questions(doc,0,dataset,catalogue))F.set(doc.episodes[0],q.path,C.ND);doc.episodes[0].answers.notes='Synthetic uncertainty for automated testing only.';doc.episodes[0].status='complete';doc.episodes[0].completed_at=new Date().toISOString();doc.annotation_status='complete';return doc;}
const tasks=approved(),draft=F.create(dataset,catalogue,tasks,'rater A'),complete=fill(C.clone(draft));let passed=0;
function test(name,fn){fn();passed++;if(!fixtureOnly)console.log('PASS '+name);}
test('default tasks unapproved with blank directions and blank human audits',()=>{const t=F.createTasks(dataset,catalogue);assert.deepStrictEqual(F.validateTasks(t,dataset,catalogue),[]);assert(F.validateTasks(t,dataset,catalogue,true).length);assert.strictEqual(t.layout.episodes[0].directions[0].text,'');assert.strictEqual(t.audits['unit-episode'].glass.pane_present,null);assert(!t.settings.protocol_reviewed);});
test('approved task complete annotation valid',()=>{assert.deepStrictEqual(F.validateTasks(tasks,dataset,catalogue,true),[]);assert.deepStrictEqual(F.validate(complete,dataset,catalogue,true),[]);});
test('hash ignores display coordinator/date but detects physical target/settings/audits',()=>{assert.strictEqual(F.taskId(changed(tasks,x=>{x.coordinator='Renamed';x.created_at='2020-01-01T00:00:00Z';x.layout.coordinator='Renamed';x.layout.created_at=x.created_at;})),tasks.task_id);for(const fn of [t=>t.layout.episodes[0].markers[0].x=.2,t=>t.settings.protocol_notes+=' changed',t=>t.audits['unit-episode'].trajectory.valid='yes'])assert.notStrictEqual(F.taskId(changed(tasks,fn)),tasks.task_id);});
test('edited targets with stale task ID fail',()=>assert(F.validateTasks(changed(tasks,x=>x.layout.episodes[0].markers[0].x=.2),dataset,catalogue).some(e=>e.includes('identity'))));
test('draft facts allowed while researcher pending and blocked directions clear',()=>{const t=F.createTasks(dataset,catalogue),d=F.create(dataset,catalogue,t,'rater A');d.episodes[0].answers.scene.crossing_valid='yes';assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);assert(F.questions(d,0,dataset,catalogue).filter(q=>['exposure','pathways'].includes(q.section)).every(q=>q.blocked));assert(F.validateEpisode(d,0,dataset,catalogue,true).some(e=>e.includes('Researcher pending')));});
test('human answers not derived from geometry',()=>{assert.strictEqual(draft.episodes[0].answers.scene.boundary_class,null);assert.strictEqual(draft.episodes[0].answers.surfaces.I1.object_name,null);assert.strictEqual(draft.episodes[0].checks.indoor_region_correct,null);});
test('L2 does not require L3 or researcher mesh fields',()=>{const r=complete.episodes[0];assert.strictEqual(r.answers.surfaces.I1.visibility.f01,null);assert.strictEqual(r.answers.boundary.pane_in_mesh,null);assert.strictEqual(r.answers.boundary_visibility.f12.visibility,null);assert.deepStrictEqual(F.validate(complete,dataset,catalogue,true),[]);});
test('L2+3 requires all visibility fields',()=>{const d=changed(complete,x=>x.profile='l2_l3');assert(F.validate(d,dataset,catalogue,true).some(e=>e.includes('visibility.f12')));fill(d);assert.deepStrictEqual(F.validate(d,dataset,catalogue,true),[]);});
test('two certified pre-crossing visibility frames mandatory in L2',()=>assert(F.validate(changed(complete,x=>x.episodes[0].answers.boundary_visibility.f01.object_match=null),dataset,catalogue,true).some(e=>e.includes('object_match'))));
test('all directions/open-sealed/channels in descriptors with explicit context',()=>{const qs=F.questions(draft,0,dataset,catalogue),ex=qs.filter(q=>q.section==='exposure'),p=qs.filter(q=>q.section==='pathways');assert.strictEqual(ex.length,48);assert.strictEqual(p.length,16);for(const q of [...ex,...p]){assert(q.direction.text&&q.condition_text&&q.frame_id);assert.strictEqual(q.blocked,false);assert(q.options.some(o=>o.value===C.ND));}});
test('all categorical descriptors include Not sure',()=>{for(const q of F.questions(draft,0,dataset,catalogue).filter(q=>q.kind==='choice'||q.kind==='hierarchy'))assert(q.options.some(o=>o.value===C.ND),q.path);});
test('hierarchy descriptors expose material catalogue rather than only Other/ND',()=>{for(const q of F.questions(draft,0,dataset,catalogue).filter(q=>q.path.endsWith('hierarchy_id'))){assert.strictEqual(q.kind,'hierarchy');assert(q.options.some(o=>o.value==='wood'&&o.label==='Wooden installed panel'));}});
test('unapproved placeholder directions cannot become answerable through approval flags',()=>{const t=rehash(changed(tasks,x=>x.layout.episodes[0].directions[0].text='UNAPPROVED DRAFT: from [name the visible reference feature].'));assert(!F.episodeReady(t,0,dataset,catalogue).ready);assert(F.validateTasks(t,dataset,catalogue,true).some(e=>e.includes('placeholder')));assert(F.questions(F.create(dataset,catalogue,t,'rater A'),0,dataset,catalogue).filter(q=>q.section==='exposure').every(q=>q.blocked));});
test('substrate fields conditional on known=yes',()=>{assert(!F.questions(draft,0,dataset,catalogue).some(q=>q.path==='answers.surfaces.I1.substrate_material'));const d=changed(complete,x=>x.episodes[0].answers.surfaces.I1.substrate_known='yes');assert(F.validate(d,dataset,catalogue,true).some(e=>e.includes('substrate_material')));d.episodes[0].answers.surfaces.I1.substrate_material='Wood';d.episodes[0].answers.surfaces.I1.substrate_hierarchy_id='wood';assert.deepStrictEqual(F.validate(d,dataset,catalogue,true),[]);});
test('ND is explicit and requires one episode reason',()=>{assert(F.validate(changed(complete,x=>x.episodes[0].answers.notes=''),dataset,catalogue,true).some(e=>e.includes('short explanation')));assert.strictEqual(complete.episodes[0].answers.scene.crossing_valid,C.ND);});
test('skip remains missing and cannot masquerade as complete',()=>assert(F.validate(changed(complete,x=>x.episodes[0].checks.indoor_region_correct=null),dataset,catalogue,true).length));
test('invalid enum and unknown hierarchy rejected in draft',()=>{for(const fn of [d=>d.episodes[0].answers.scene.shelter='blue',d=>d.episodes[0].checks.surfaces.I1.obstruction='bad',d=>d.episodes[0].answers.surfaces.I1.hierarchy_id='unknown'])assert(F.validate(changed(draft,fn),dataset,catalogue).length);});
test('prototype pollution and malformed documents rejected',()=>{const bad=JSON.parse(JSON.stringify(draft));bad.ui=JSON.parse('{"__proto__":{"polluted":true}}');assert(F.validate(bad,dataset,catalogue).some(e=>e.includes('forbidden')));for(const v of [null,[],{},changed(draft,x=>x.episodes[0]=null)])assert(F.validate(v,dataset,catalogue).length);assert.strictEqual({}.polluted,undefined);});
test('reference hierarchy hash tampering rejected even after task rehash',()=>{const t=rehash(changed(tasks,x=>x.settings.hierarchy_sha256='tampered'));assert(F.validateTasks(t,dataset,catalogue).some(e=>e.includes('catalogue hash')));});
test('approval without reviewer rejected',()=>assert(F.validateTasks(rehash(changed(tasks,x=>x.settings.protocol_reviewer='')),dataset,catalogue).some(e=>e.includes('reviewer'))));
test('VHC pending does not block collection and does not enable C',()=>{assert.strictEqual(tasks.settings.vhc_allowed_pairs_status,'not_supplied');assert(F.episodeReady(tasks,0,dataset,catalogue).ready);const report=F.consensus(complete,changed(complete,x=>x.annotator='rater B'),dataset,catalogue);assert.strictEqual(report.episodes[0].family_annotation_coverage.C.enabled,false);});
test('simple export migrates own labels by exact target geometry',()=>{const src=G.create(dataset,catalogue,'rater A');src.episodes[0].answers.surfaces.I1.material='wood';src.episodes[0].answers.scene.crossing_valid='yes';const {doc,report}=F.migrate(src,tasks,dataset,catalogue,'rater A');assert.strictEqual(doc.episodes[0].answers.surfaces.I1.material,'wood');assert.strictEqual(doc.episodes[0].answers.scene.crossing_valid,'yes');assert.strictEqual(doc.episodes[0].answers.surfaces.I1.reachable.d1.open.sun,null);assert.strictEqual(report.matched_markers,6);assert.strictEqual(doc.migration_log[0].source_sha256,crypto.createHash('sha256').update(C.stableStringify(src)).digest('hex'));});
test('foreign annotator import rejected',()=>assert.throws(()=>F.migrate(draft,tasks,dataset,catalogue,'Someone else'),/own annotation/));
test('moved point does not inherit labels despite same ID',()=>{const src=changed(draft,d=>d.episodes[0].answers.surfaces.I1.material='wood'),t=rehash(changed(tasks,x=>x.layout.episodes[0].markers[0].x=.12)),out=F.migrate(src,t,dataset,catalogue,'rater A');assert.strictEqual(out.doc.episodes[0].answers.surfaces.I1.material,null);assert.strictEqual(out.report.unmatched_markers,1);});
test('renamed identical target migrates, native-object mismatch does not',()=>{const src=changed(draft,d=>d.episodes[0].answers.surfaces.I1.material='wood');const t=rehash(changed(tasks,x=>x.layout.episodes[0].markers[0].id='I9'));assert.strictEqual(F.migrate(src,t,dataset,catalogue,'rater A').doc.episodes[0].answers.surfaces.I9.material,'wood');const other=rehash(changed(tasks,x=>x.layout.episodes[0].markers[0].object_id=2));assert.strictEqual(F.migrate(src,other,dataset,catalogue,'rater A').doc.episodes[0].answers.surfaces.I1.material,null);});
test('ambiguous duplicate targets cannot inherit same source label',()=>{const t=rehash(changed(tasks,x=>{x.layout.episodes[0].markers[1].x=x.layout.episodes[0].markers[0].x;x.layout.episodes[0].setup_reviewed=false;})),src=changed(draft,d=>d.episodes[0].answers.surfaces.I1.material='wood');const out=F.migrate(src,t,dataset,catalogue,'rater A');assert.strictEqual(out.doc.episodes[0].answers.surfaces.I1.material,null);assert.strictEqual(out.doc.episodes[0].answers.surfaces.I2.material,null);});
test('direction edit clears exposure/pathways, preserves material facts',()=>{const src=changed(draft,d=>{d.episodes[0].answers.surfaces.I1.material='wood';d.episodes[0].answers.surfaces.I1.reachable.d1.open.sun='yes';d.episodes[0].answers.pathways.d1.open.rain='no';}),t=rehash(changed(tasks,x=>x.layout.episodes[0].directions[0].text+=' different'));const out=F.migrate(src,t,dataset,catalogue,'rater A').doc;assert.strictEqual(out.episodes[0].answers.surfaces.I1.material,'wood');assert.strictEqual(out.episodes[0].answers.surfaces.I1.reachable.d1.open.sun,null);assert.strictEqual(out.episodes[0].answers.pathways.d1.open.rain,null);});
test('observation edit clears correspondence/visibility without clearing material',()=>{const src=changed(draft,d=>{d.episodes[0].answers.surfaces.I1.material='wood';d.episodes[0].answers.surfaces.I1.visibility.f02='direct';d.episodes[0].checks.surfaces.I1.same_surface_across_frames='yes';}),t=rehash(changed(tasks,x=>x.layout.episodes[0].markers[0].observations.push({frame_id:'f02',x:.4,y:.4,source:'human'}))),out=F.migrate(src,t,dataset,catalogue,'rater A').doc;assert.strictEqual(out.episodes[0].answers.surfaces.I1.material,'wood');assert.strictEqual(out.episodes[0].answers.surfaces.I1.visibility.f02,null);assert.strictEqual(out.episodes[0].checks.surfaces.I1.same_surface_across_frames,null);});
test('boundary outline edit clears boundary identity and dependent physics, not unchanged surface material',()=>{const src=changed(draft,d=>{d.episodes[0].answers.boundary.object_identity_correct='yes';d.episodes[0].answers.boundary.material='glass';d.episodes[0].answers.surfaces.I1.material='wood';d.episodes[0].answers.pathways.d1.open.rain='yes';d.episodes[0].answers.surfaces.I1.reachable.d1.open.rain='yes';}),t=rehash(changed(tasks,x=>x.layout.episodes[0].boundary_boxes[0].x0=.05)),out=F.migrate(src,t,dataset,catalogue,'rater A').doc;assert.strictEqual(out.episodes[0].answers.boundary.object_identity_correct,null);assert.strictEqual(out.episodes[0].answers.boundary.material,null);assert.strictEqual(out.episodes[0].answers.pathways.d1.open.rain,null);assert.strictEqual(out.episodes[0].answers.surfaces.I1.reachable.d1.open.rain,null);assert.strictEqual(out.episodes[0].answers.surfaces.I1.material,'wood');});
test('legacy advanced export supported and completion invalidated',()=>{const legacy=C.createExport(dataset,tasks.layout,'rater A');legacy.episodes[0].answers.surfaces.I1.material='wood';const out=F.migrate(legacy,tasks,dataset,catalogue,'rater A').doc;assert.strictEqual(out.schema,F.SCHEMA);assert.strictEqual(out.episodes[0].status,'in_progress');assert.strictEqual(out.episodes[0].completed_at,null);assert.strictEqual(out.episodes[0].answers.surfaces.I1.material,'wood');});
test('two-rater consensus retains disagreement and agreed ND separately',()=>{const second=changed(complete,d=>{d.annotator='rater B';d.episodes[0].answers.scene.crossing_valid='no';}),c=F.consensus(complete,second,dataset,catalogue);assert.strictEqual(c.episodes[0].fields['scene.crossing_valid'].state,'disagreement');assert.strictEqual(c.episodes[0].fields['scene.boundary_class'].state,'agreed_not_determinable');assert.strictEqual(c.episodes[0].fields['surfaces.I1.visibility.f12'].state,'not_applicable');assert.strictEqual(c.episodes[0].fields['scene.boundary_class'].eligible_known_gt,false);});
test('consensus rejects same ID, task mismatch and profile mismatch',()=>{assert.throws(()=>F.consensus(complete,complete,dataset,catalogue),/distinct/);const t=rehash(changed(tasks,x=>x.audits['unit-episode'].trajectory.valid='yes')),other=fill(F.create(dataset,catalogue,t,'rater B'));assert.throws(()=>F.consensus(complete,other,dataset,catalogue),/same shared/);const l3=fill(F.create(dataset,catalogue,tasks,'rater B','l2_l3'));assert.throws(()=>F.consensus(complete,l3,dataset,catalogue),/same shared/);});
function boundaryKnown(){const d=C.clone(complete),a=d.episodes[0].answers,c=d.episodes[0].checks;Object.assign(a.scene,{crossing_valid:'yes',canonical_context_clear:'yes',boundary_class:'outdoor'});Object.assign(c,{indoor_region_correct:'yes',exterior_region_correct:'yes'});Object.assign(a.boundary,{object_identity_correct:'yes',kind:'hinged_door',observed_state:'closed',material:'wood',pane_transparency:'opaque',glazing:'absent'});for(const f of ['f01','f02'])Object.assign(a.boundary_visibility[f],{visibility:'direct',object_match:'yes',box_correct:'yes'});for(const direction of C.DIRECTIONS)for(const state of C.STATES)for(const channel of ['direct_sun','diffuse_light','air','rain'])a.pathways[direction][state][channel]='no';return d;}
const pair=d=>F.consensus(d,changed(d,x=>x.annotator='rater B'),dataset,catalogue).episodes[0];
test('B coverage requires certified visible witnesses, not reflection or machine pixels',()=>{const d=boundaryKnown();assert(pair(d).family_annotation_coverage.B.pathway_labels_available);d.episodes[0].answers.boundary_visibility.f01.visibility='reflection';assert(!pair(d).family_annotation_coverage.B.pathway_labels_available);});
test('no existing closure cannot provide sealed B coverage',()=>{const d=boundaryKnown();d.episodes[0].answers.boundary.observed_state='no_closure';assert(!pair(d).family_annotation_coverage.B.pathway_labels_available);});
test('mutually agreed but contradictory boundary answers do not become B-ready',()=>{for(const fn of [d=>d.episodes[0].answers.boundary.pane_transparency='clear',d=>d.episodes[0].answers.pathways.d1.sealed.air='yes']){const d=changed(boundaryKnown(),fn),e=pair(d);assert(!e.family_annotation_coverage.B.pathway_labels_available);assert(e.family_annotation_coverage.B.consistency_review_required);assert(e.consistency_warnings.length);}});
test('an external VHC approval flag cannot enable an absent mapping table',()=>{const t=rehash(changed(tasks,x=>x.settings.vhc_allowed_pairs_status='approved_external')),d=fill(F.create(dataset,catalogue,t,'rater A'));assert.strictEqual(pair(d).family_annotation_coverage.C.enabled,false);});
test('excluded scenes need explicit reason and remain excluded in consensus',()=>{const doc=changed(draft,d=>{d.episodes[0].status='excluded';d.annotation_status='complete';});assert(F.validate(doc,dataset,catalogue,true).some(e=>e.includes('reason')));doc.episodes[0].exclusion_reason='Target is unusable';assert.deepStrictEqual(F.validate(doc,dataset,catalogue,true),[]);const c=F.consensus(doc,changed(doc,d=>d.annotator='rater B'),dataset,catalogue);assert(c.episodes[0].excluded);assert.strictEqual(c.agreement_by_attribute['scene.crossing_valid'].n_excluded,1);});
test('question paths setter cannot add unknown/prototype properties',()=>{assert.throws(()=>F.set(draft.episodes[0],'answers.__proto__.oops','yes'));assert.throws(()=>F.set(draft.episodes[0],'answers.scene.fake','yes'));});
if(fixtureOnly)process.stdout.write(JSON.stringify({dataset,catalogue,tasks,draft,complete,second:changed(complete,d=>d.annotator='rater B')}));
else console.log(JSON.stringify({passed}));
