'use strict';
const assert=require('assert'),C=require('../core.js'),F=require('../full-core.js'),R=require('../redpoint-core.js');
const dataset={build_id:'redpoint-test',episodes:[{id:'scene1',frames:C.FRAMES.map((id,index)=>({id,side:index<6?'indoor':'exterior',instance_map:'data/instances/'+id+'.png',boundary_pixels:150,boundary_bbox:[.1,.1,.5,.6],objects:[{object_id:1,mpcat40:2},{object_id:2,mpcat40:1}]})),proposed_markers:['indoor','exterior'].flatMap(side=>[1,2,3,4].map(n=>({id:(side==='indoor'?'I':'E')+n,side,anchor_frame:side==='indoor'?'f01':'f07',x:n/5,y:.3,object_id:1,mpcat40:2,observations:[]})))}]};
const catalogue={build_id:dataset.build_id,objects:[{id:-1,name:'unknown'},{id:0,name:'void'},{id:1,name:'wall'},{id:2,name:'floor'}],materials:[{id:'wood',name:'Wood panel',description:'Wood panel installed surface'}]};
const copy=C.clone;
const tasks=F.createTasks(dataset,catalogue,'Researcher');
Object.assign(tasks.settings,{hierarchy_reviewed:true,hierarchy_reviewer:'Researcher',protocol_reviewed:true,protocol_reviewer:'Researcher'});
Object.assign(tasks.layout.episodes[0],{setup_reviewed:true,directions:[{id:'d1',text:'From the left tree toward the door',reference_frame:'f07',x:.2,y:.3},{id:'d2',text:'From the right wall toward the door',reference_frame:'f07',x:.8,y:.3}]});
const rehash=task=>{task.layout.layout_id='';task.task_id=F.taskId(task);return task;};rehash(tasks);
const draft=F.create(dataset,catalogue,tasks,'A');
function automatic(doc,sample={width:160,height:128,object_id:1}){return doc.tasks.layout.episodes.flatMap(ep=>ep.markers.map(marker=>R.createAutomaticLabel({episode_id:ep.episode_id,marker,frame:dataset.episodes[0].frames.find(f=>f.id===marker.anchor_frame),catalogue,sample})));}
function attach(doc){doc.automatic_surface_labels=automatic(doc);doc.surface_label_audit=R.buildSurfaceLabelAudit(doc,dataset,catalogue);return doc;}
function complete(doc){for(const q of F.questions(doc,0,dataset,catalogue))F.setAnswer(doc,0,q.path,q.kind==='multiselect'?[C.ND]:C.ND);doc.episodes[0].answers.notes='Synthetic uncertainty test';doc.episodes[0].status='complete';doc.episodes[0].completed_at=new Date().toISOString();doc.annotation_status='complete';return doc;}
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('lattice, solid roof, open sky and historic partial remain distinct',()=>{assert.deepStrictEqual(C.FIELDS.shelter,['overhead','slats_lattice','none','partial',C.ND]);for(const q of F.questions(draft,0,dataset,catalogue).filter(q=>q.path.endsWith('.shelter'))){const labels=Object.fromEntries(q.options.map(o=>[o.value,o.label]));assert.strictEqual(labels.slats_lattice,'Slats or lattice (partial)');assert.strictEqual(labels.overhead,'Solid roof / overhang');assert.strictEqual(labels.none,'Open sky');assert.strictEqual(labels.partial,'Other partial cover');}});
test('new lattice enum and old partial both validate without changing saved labels',()=>{for(const shelter of ['partial','slats_lattice']){const d=copy(draft);d.episodes[0].answers.scene.shelter=shelter;d.episodes[0].answers.surfaces.I1.shelter=shelter;assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);const migrated=F.migrate(d,tasks,dataset,catalogue,'A').doc;assert.strictEqual(migrated.episodes[0].answers.surfaces.I1.shelter,shelter);}});
test('legacy files without machine metadata remain valid',()=>assert.deepStrictEqual(F.validate(draft,dataset,catalogue),[]));
test('actual instance sample resolves catalogue label and exact anchor pixel',()=>{const row=automatic(draft)[0];assert.strictEqual(row.status,'sampled');assert.strictEqual(row.object_id,1);assert.strictEqual(row.mpcat40_id,2);assert.strictEqual(row.mpcat40_name,'floor');assert.strictEqual(row.pixel_x,32);assert.strictEqual(row.pixel_y,38);assert.strictEqual(row.source_path,'data/instances/f01.png');});
test('machine metadata creates no human answers',()=>{const d=attach(copy(draft));assert.strictEqual(d.episodes[0].answers.surfaces.I1.object_name,null);assert.strictEqual(d.surface_label_audit[0].human.material,null);assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('background, unmapped and failed masks cannot invent labels',()=>{for(const [sample,status]of [[null,'unavailable'],[{width:160,height:128,object_id:-1},'background'],[{width:160,height:128,object_id:99},'unmapped_instance']]){const rows=automatic(draft,sample);assert(rows.every(row=>row.status===status&&row.mpcat40_id===null&&row.mpcat40_name===null));assert.deepStrictEqual(R.validateAutomaticLabels(rows,tasks,dataset,catalogue),[]);}});
test('missing or duplicate automatic rows are rejected',()=>{let rows=automatic(draft);rows.pop();assert(R.validateAutomaticLabels(rows,tasks,dataset,catalogue).length);rows=automatic(draft);rows.push(copy(rows[0]));assert(R.validateAutomaticLabels(rows,tasks,dataset,catalogue).length);});
test('tampered category, name, coordinates, source and status are rejected',()=>{for(const [key,value]of [['mpcat40_id',1],['mpcat40_name','wood'],['pixel_x',100],['x',.6],['source_path','wrong.png'],['anchor_frame','f02'],['status','background'],['width',null]]){const rows=automatic(draft);rows[0][key]=value;assert(R.validateAutomaticLabels(rows,tasks,dataset,catalogue).length,key);}});
test('lookup is bound to actual anchor frame object metadata',()=>{const rows=automatic(draft),changed=copy(dataset);changed.episodes[0].frames[0].objects=[];assert(R.validateAutomaticLabels(rows,tasks,changed,catalogue).length);});
test('machine labels and human choices are paired without object-material comparison',()=>{const d=copy(draft);Object.assign(d.episodes[0].answers.surfaces.I1,{object_name:' Floor ',material:'painted timber',hierarchy_id:'wood'});attach(d);const row=d.surface_label_audit[0];assert.strictEqual(row.comparison.status,'agree');assert.strictEqual(row.human.material,'painted timber');d.episodes[0].answers.surfaces.I1.object_name='WALL';d.surface_label_audit=R.buildSurfaceLabelAudit(d,dataset,catalogue);assert.strictEqual(d.surface_label_audit[0].comparison.status,'disagree');assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('free descriptions, material words and uncertainty stay unscorable',()=>{const automaticLabel=automatic(draft)[0];for(const object_name of [null,'wood','wood floor','unknown','void',C.ND,'not sure'])assert.strictEqual(R.compareObjectLabel(automaticLabel,{object_name},catalogue).eligible,false);});
test('excluded scenes never contribute categorical mismatch rates',()=>{const d=attach(copy(draft));d.episodes[0].status='excluded';d.episodes[0].exclusion_reason='Test';d.episodes[0].answers.surfaces.I1.object_name='wall';d.surface_label_audit=R.buildSurfaceLabelAudit(d,dataset,catalogue);assert.strictEqual(d.surface_label_audit[0].comparison.reason,'episode_excluded');assert.strictEqual(d.surface_label_audit[0].comparison.eligible,false);});
test('metadata fields must appear together and stale audit snapshots reject',()=>{const d=attach(copy(draft));delete d.surface_label_audit;assert(F.validate(d,dataset,catalogue).some(e=>e.includes('together')));attach(d);d.episodes[0].answers.surfaces.I1.material='new text';assert(F.validate(d,dataset,catalogue).some(e=>e.includes('stale')));d.surface_label_audit=R.buildSurfaceLabelAudit(d,dataset,catalogue);assert.deepStrictEqual(F.validate(d,dataset,catalogue),[]);});
test('automatic labels do not become votes in two-rater agreement',()=>{const a=complete(copy(draft)),b=copy(a);b.annotator='B';const old=F.consensus(a,b,dataset,catalogue);attach(a);attach(b);const added=F.consensus(a,b,dataset,catalogue);assert.deepStrictEqual(added.agreement_by_attribute,old.agreement_by_attribute);assert.deepStrictEqual(added.episodes[0].fields,old.episodes[0].fields);});
test('explicit four-per-side policy admits four and rejects three only when ready',()=>{const strict=copy(tasks);strict.settings.points_per_side=4;rehash(strict);assert.deepStrictEqual(F.validateTasks(strict,dataset,catalogue,true),[]);assert(F.episodeReady(strict,0,dataset,catalogue).ready);strict.layout.episodes[0].markers.pop();rehash(strict);assert.deepStrictEqual(F.validateTasks(strict,dataset,catalogue),[]);assert(F.validateTasks(strict,dataset,catalogue,true).some(e=>e.includes('exactly 4')));assert(!F.episodeReady(strict,0,dataset,catalogue).ready);delete strict.settings.points_per_side;rehash(strict);assert.deepStrictEqual(F.validateTasks(strict,dataset,catalogue,true),[]);});
test('invalid point policy and stale task hash are rejected',()=>{const t=copy(tasks);t.settings.points_per_side=5;rehash(t);assert(F.validateTasks(t,dataset,catalogue).some(e=>e.includes('expected exactly 4')));t.settings.points_per_side=4;assert(F.validateTasks(t,dataset,catalogue).some(e=>e.includes('identity')));});
console.log(JSON.stringify({passed}));
